'use client'

import { useMemo, useState, type ClipboardEvent, type ChangeEvent } from 'react'
import { DEFAULT_PUBLIC_AUTHOR_NAME } from '@/lib/cached-queries'
import { parseBulkThreadDraft, BULK_THREAD_COMMENT_LIMIT } from '@/lib/thread-bulk-create'
import { createConsentedBulkThread } from './actions'

type Item = { id: string; body: string; internalMemo: string; permissionConfirmedOn: string; textState: 'original' | 'lightly_edited' }
const today = () => new Date().toISOString().slice(0, 10)
const makeItem = (body = ''): Item => ({ id: crypto.randomUUID(), body, internalMemo: '', permissionConfirmedOn: today(), textState: 'original' })

export function ThreadBulkCreateClient() {
  const [raw, setRaw] = useState(''); const [title, setTitle] = useState(''); const [body, setBody] = useState('')
  const [items, setItems] = useState<Item[]>([]); const [parsed, setParsed] = useState(false)
  const [image, setImage] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const imageUrl = useMemo(() => image ? URL.createObjectURL(image) : '', [image])
  const choose = (file?: File) => { if (file?.type.startsWith('image/')) setImage(file) }
  const onPaste = (event: ClipboardEvent<HTMLDivElement>) => { const file = [...event.clipboardData.items].find(i => i.type.startsWith('image/'))?.getAsFile(); if (file) { event.preventDefault(); choose(file) } }
  const update = (id: string, patch: Partial<Item>) => setItems(all => all.map(item => item.id === id ? { ...item, ...patch } : item))
  const move = (index: number, offset: number) => setItems(all => { const next = [...all]; const target = index + offset; if (target < 0 || target >= next.length) return all; [next[index], next[target]] = [next[target], next[index]]; return next })
  const analyze = () => { const value = parseBulkThreadDraft(raw); if (!value) { setParsed(false); setMessage('タイトル・本文・コメントの見出しを確認してください。'); return } setTitle(value.title); setBody(value.body); setItems(value.comments.map(makeItem)); setParsed(true); setMessage('') }
  const submit = async () => { if (!parsed || busy || !title.trim()) return; if (!confirm(`スレッド1件とコメント${items.filter(i => i.body.trim()).length}件を登録します。`)) return; setBusy(true); setMessage(''); const fd = new FormData(); fd.set('title', title); fd.set('body', body); fd.set('comments', JSON.stringify(items)); if (image) fd.set('image', image); const result = await createConsentedBulkThread(fd); setBusy(false); setMessage(result.message); if (result.threadId) location.href = `/thread/${result.threadId}` }
  return <div onPaste={onPaste} className="space-y-4">
    <section className="rounded border bg-white p-3"><label className="mb-2 block font-bold">原稿を貼り付け</label><textarea value={raw} onChange={e => setRaw(e.target.value)} rows={14} className="w-full rounded border p-2 font-mono text-sm" placeholder="タイトル：&#10;...&#10;&#10;本文：&#10;...&#10;&#10;コメント：&#10;1&#10;..."/><button onClick={analyze} className="mt-2 rounded bg-blue-600 px-4 py-2 font-bold text-white">原稿を解析</button></section>
    {parsed && <><section className="space-y-3 rounded border bg-white p-3"><label className="block font-bold">タイトル<input value={title} maxLength={100} onChange={e => setTitle(e.target.value)} className="mt-1 w-full rounded border p-2 font-normal"/></label><label className="block font-bold">本文<textarea value={body} maxLength={5000} onChange={e => setBody(e.target.value)} rows={5} className="mt-1 w-full rounded border p-2 font-normal"/></label>
      <div><div className="mb-1 font-bold">スレ画（1枚・ファイル選択またはCtrl+V）</div><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={(e: ChangeEvent<HTMLInputElement>) => choose(e.target.files?.[0])}/>{image && <div className="mt-2"><img src={imageUrl} alt="スレ画プレビュー" className="max-h-64 rounded object-contain"/><button onClick={() => setImage(null)} className="mt-1 text-red-600">削除</button></div>}</div></section>
      <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold">コメント（{items.length}/{BULK_THREAD_COMMENT_LIMIT}）</h2><button disabled={items.length >= BULK_THREAD_COMMENT_LIMIT} onClick={() => setItems(v => [...v, makeItem()])} className="rounded border bg-white px-3 py-1">＋追加</button></div>{items.map((item, index) => <article key={item.id} className="rounded border bg-white p-3"><div className="mb-2 flex items-center justify-between"><b>#{index + 2}</b><div className="space-x-2"><button onClick={() => move(index, -1)} disabled={!index}>↑</button><button onClick={() => move(index, 1)} disabled={index === items.length - 1}>↓</button><button onClick={() => setItems(v => v.filter(x => x.id !== item.id))} className="text-red-600">削除</button></div></div><textarea value={item.body} maxLength={5000} onChange={e => update(item.id, { body: e.target.value })} rows={4} className="w-full rounded border p-2"/><div className="mt-2 grid gap-2 sm:grid-cols-3"><label>許可確認日<input type="date" value={item.permissionConfirmedOn} onChange={e => update(item.id, { permissionConfirmedOn: e.target.value })} className="block w-full rounded border p-2"/></label><label>文面<select value={item.textState} onChange={e => update(item.id, { textState: e.target.value as Item['textState'] })} className="block w-full rounded border p-2"><option value="original">元文のまま</option><option value="lightly_edited">軽微な整文済み</option></select></label><label>内部メモ<input value={item.internalMemo} onChange={e => update(item.id, { internalMemo: e.target.value })} className="block w-full rounded border p-2"/></label></div></article>)}</section>
      <section className="rounded border-2 border-blue-200 bg-white p-3"><h2 className="mb-3 text-lg font-bold">公開プレビュー</h2><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 whitespace-pre-wrap">{body}</p>{image && <img src={imageUrl} alt="" className="mt-3 max-h-80 object-contain"/>}<p className="my-3 font-bold">コメント {items.filter(i => i.body.trim()).length}件</p>{items.filter(i => i.body.trim()).map((item, i) => <div key={item.id} className="border-t py-3"><div className="text-xs text-gray-500">{i + 2} {DEFAULT_PUBLIC_AUTHOR_NAME}</div><p className="mt-1 whitespace-pre-wrap">{item.body}</p></div>)}</section>
      <button disabled={busy || !title.trim()} onClick={submit} className="w-full rounded bg-green-700 px-4 py-3 font-bold text-white disabled:opacity-50">{busy ? '登録中…' : '登録する'}</button></>}{message && <p role="alert" className="rounded bg-yellow-50 p-3">{message}</p>}
  </div>
}
