// 思い出図鑑「殿堂・プレミアム殿堂図鑑」特集の静的データ。
//
// これは公式の最新殿堂レギュレーション一覧ではなく、
// 過去に環境へ大きな影響を与えた殿堂カードを振り返る思い出図鑑内の特集ページ用データ。
// 文章はDMWiki等から転載せず、事実データ（指定日・履歴）のみを扱う。
//
// 将来、他の施行日を追加する場合は HALL_OF_FAME_ENTRIES に HallEntry を1件足すだけでよい。

/** 殿堂特集に載せる1枚分のカード情報 */
export type HallCard = {
  /** カード名（《》は表示側で付与しない。データ内に含める） */
  name: string
  /** その施行日で起きた状態変更（このページの主役表示）。例: 「無制限 → 殿堂入り」。表示ラベルは付けない */
  initial: string
  /** その後の変遷（任意。施行日以降にさらに変動した場合の概要） */
  later?: string
  /** カードの簡単な説明 */
  description: string
  /** 履歴（無制限/殿堂入り/プレミアム殿堂…の時系列ステップ） */
  history: string[]
  /** 公式カード画像URL（任意。未設定や読み込み失敗時はプレースホルダ表示） */
  imageUrl?: string
  /** 公式カード詳細ページURL（任意。出典リンク／画像クリック先） */
  officialUrl?: string
  /**
   * 複数カード画像（任意）。プレミアム殿堂コンビなど複数枚を並べたい場合に使う。
   * 設定されている場合は imageUrl の1枚表示ではなく、これらを横並び（スマホは横スクロール）で表示する。
   */
  images?: { src: string; name: string }[]
}

// 公式カード画像・詳細ページのURLを id から組み立てる（外部APIは使わず静的に保持）。
const officialImage = (id: string) => `https://dm.takaratomy.co.jp/wp-content/card/cardimage/${id}.jpg`
const officialPage = (id: string) => `https://dm.takaratomy.co.jp/card/detail/?id=${id}`

/** 1施行日分の殿堂特集エントリ */
export type HallEntry = {
  /** URLスラッグ兼識別子。例: '2004-03-15' */
  slug: string
  /** 表示用の施行日ラベル。例: '2004年3月15日' */
  dateLabel: string
  /** ページタイトル */
  title: string
  /** ページ説明 */
  description: string
  /** この施行日で指定されたカード一覧 */
  cards: HallCard[]
}

export const OFFICIAL_REGULATION_URL = 'https://dm.takaratomy.co.jp/rule/regulation/'

export type CurrentHallCard = HallCard & { status: 'hall' | 'premium' }

export function getHallCardOfficialId(card: HallCard): string | null {
  const url = card.officialUrl ?? card.imageUrl
  if (!url) return null
  return url.match(/[?&]id=([^&]+)/)?.[1] ?? url.match(/\/([^/]+)\.jpg$/)?.[1] ?? null
}

/** 履歴の末尾を現在状態として、現在も単体規制中のカードだけを返す。 */
export function getCurrentHallCards(): CurrentHallCard[] {
  const byName = new Map<string, CurrentHallCard>()
  for (const entry of HALL_OF_FAME_ENTRIES) {
    for (const card of entry.cards) {
      const current = card.history.at(-1)
      if (current !== '殿堂入り' && current !== 'プレミアム殿堂') {
        byName.delete(card.name)
        continue
      }
      byName.set(card.name, { ...card, status: current === '殿堂入り' ? 'hall' : 'premium' })
    }
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name, 'ja'))
}

export const HALL_OF_FAME_ENTRIES: HallEntry[] = [
  {
    slug: '2004-03-15',
    dateLabel: '2004年3月15日',
    title: '2004年3月15日 殿堂発表',
    description: 'デュエル・マスターズ初期に初めて殿堂入りしたカードたちを振り返るページです。',
    cards: [
      {
        name: '《サイバー・ブレイン》',
        initial: '無制限 → 殿堂入り',
        later: 'プレミアム殿堂 → 殿堂入り → 無制限',
        description: '初期デュエマを代表する強力ドロー呪文。',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-052'),
        officialUrl: officialPage('dm01-052'),
      },
      {
        name: '《アストラル・リーフ》',
        initial: '無制限 → 殿堂入り',
        later: '無制限',
        description: '青単速攻や進化クリーチャーの象徴的存在。',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-002'),
        officialUrl: officialPage('dm04-002'),
      },
      {
        name: '《エメラル》',
        initial: '無制限 → 殿堂入り',
        description: 'シールド操作で多くのデッキに採用されたカード。',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm03-042'),
        officialUrl: officialPage('dm03-042'),
      },
      {
        name: '《ストリーミング・シェイパー》',
        initial: '無制限 → 殿堂入り',
        description: '水文明デッキの手札補充を支えた呪文。',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm03-011'),
        officialUrl: officialPage('dm03-011'),
      },
      {
        name: '《ディープ・オペレーション》',
        initial: '無制限 → 殿堂入り',
        later: '無制限',
        description: '大量ドローが狙える初期の水文明呪文。',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm02-026'),
        officialUrl: officialPage('dm02-026'),
      },
    ],
  },
  {
    slug: '2005-03-15',
    dateLabel: '2005年3月15日',
    title: '2005年3月15日 殿堂発表',
    description: '2005年3月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アクアン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-010'),
        officialUrl: officialPage('dm04-010'),
      },
    ],
  },
  {
    slug: '2005-07-15',
    dateLabel: '2005年7月15日',
    title: '2005年7月15日 殿堂発表',
    description: '2005年7月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《スケルトン・バイス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm08-014'),
        officialUrl: officialPage('dm08-014'),
      },
      {
        name: '《無双竜機ボルバルザーク》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-009'),
        officialUrl: officialPage('dm10-009'),
      },
      {
        name: '《ヘル・スラッシュ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm06-057'),
        officialUrl: officialPage('dm06-057'),
      },
      {
        name: '《ロスト・チャージャー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm09-014'),
        officialUrl: officialPage('dm09-014'),
      },
    ],
  },
  {
    slug: '2006-03-15',
    dateLabel: '2006年3月15日',
    title: '2006年3月15日 殿堂発表',
    description: '2006年3月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《炎槍と水剣の裁》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '無制限'],
        imageUrl: officialImage('dm13-031'),
        officialUrl: officialPage('dm13-031'),
      },
      {
        name: '《無双竜機ボルバルザーク》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-009'),
        officialUrl: officialPage('dm10-009'),
      },
    ],
  },
  {
    slug: '2007-01-15',
    dateLabel: '2007年1月15日',
    title: '2007年1月15日 殿堂発表',
    description: '2007年1月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ヘル・スラッシュ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm06-057'),
        officialUrl: officialPage('dm06-057'),
      },
      {
        name: '《ロスト・チャージャー》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm09-014'),
        officialUrl: officialPage('dm09-014'),
      },
      {
        name: '《ボルメテウス・サファイア・ドラゴン》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc27-004'),
        officialUrl: officialPage('dmc27-004'),
      },
      {
        name: '《フューチャー・スラッシュ》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('promoy3-023'),
        officialUrl: officialPage('promoy3-023'),
      },
    ],
  },
  {
    slug: '2007-08-15',
    dateLabel: '2007年8月15日',
    title: '2007年8月15日 殿堂発表',
    description: '2007年8月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アクア・パトロール》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dm15-002'),
        officialUrl: officialPage('dm15-002'),
      },
    ],
  },
  {
    slug: '2007-11-15',
    dateLabel: '2007年11月15日',
    title: '2007年11月15日 殿堂発表',
    description: '2007年11月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《炎槍と水剣の裁》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '無制限'],
        imageUrl: officialImage('dm13-031'),
        officialUrl: officialPage('dm13-031'),
      },
      {
        name: '《クローン・バイス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm12-026'),
        officialUrl: officialPage('dm12-026'),
      },
      {
        name: '《予言者マリエル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm08-008'),
        officialUrl: officialPage('dm08-008'),
      },
    ],
  },
  {
    slug: '2007-11-23',
    dateLabel: '2007年11月23日',
    title: '2007年11月23日 殿堂発表',
    description: '2007年11月23日の殿堂発表で指定されたプレミアム殿堂コンビを振り返るページです。',
    cards: [
      {
        // プレミアム殿堂コンビ（単体カードではなくコンビ指定）。3枚の画像を並べて表示する。
        name: '《龍仙ロマネスク》と《母なる大地》または《母なる紋章》',
        initial: '無制限 → プレミアム殿堂コンビ',
        description: '',
        history: ['無制限', 'プレミアム殿堂コンビ', '無制限'],
        imageUrl: officialImage('dm25-s04'),
        officialUrl: officialPage('dm25-s04'),
        images: [
          { src: officialImage('dm25-s04'), name: '龍仙ロマネスク' },
          { src: officialImage('dm10-036'), name: '母なる大地' },
          { src: officialImage('dmx01-010'), name: '母なる紋章' },
        ],
      },
    ],
  },
  {
    slug: '2008-04-15',
    dateLabel: '2008年4月15日',
    title: '2008年4月15日 殿堂発表',
    description: '2008年4月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アクア・ハルカス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-080'),
        officialUrl: officialPage('dm01-080'),
      },
      {
        name: '《呪紋の化身》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm07-019'),
        officialUrl: officialPage('dm07-019'),
      },
      {
        name: '《母なる大地》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-036'),
        officialUrl: officialPage('dm10-036'),
      },
      {
        name: '《魂と記憶の盾》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm11-004'),
        officialUrl: officialPage('dm11-004'),
      },
      {
        name: '《パシフィック・チャンピオン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm13-009'),
        officialUrl: officialPage('dm13-009'),
      },
      {
        name: '《インフェルノ・ゲート》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm19-027'),
        officialUrl: officialPage('dm19-027'),
      },
      {
        name: '《インフィニティ・ドラゴン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm22-015'),
        officialUrl: officialPage('dm22-015'),
      },
      {
        name: '《超竜バジュラ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm08-s04'),
        officialUrl: officialPage('dm08-s04'),
      },
    ],
  },
  {
    slug: '2008-10-15',
    dateLabel: '2008年10月15日',
    title: '2008年10月15日 殿堂発表',
    description: '2008年10月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《バジュラズ・ソウル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm15-s04'),
        officialUrl: officialPage('dm15-s04'),
      },
      {
        name: '《凶星王ダーク・ヒドラ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('sp-005'),
        officialUrl: officialPage('sp-005'),
      },
      {
        name: '《スケルトン・バイス》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm08-014'),
        officialUrl: officialPage('dm08-014'),
      },
    ],
  },
  {
    slug: '2009-04-15',
    dateLabel: '2009年4月15日',
    title: '2009年4月15日 殿堂発表',
    description: '2009年4月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《凶星王ダーク・ヒドラ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('sp-005'),
        officialUrl: officialPage('sp-005'),
      },
      {
        name: '《母なる大地》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-036'),
        officialUrl: officialPage('dm10-036'),
      },
      {
        name: '《雷鳴の守護者ミスト・リエス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('promoy1-019'),
        officialUrl: officialPage('promoy1-019'),
      },
      {
        name: '《ソウル・アドバンテージ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm28-027'),
        officialUrl: officialPage('dm28-027'),
      },
      {
        name: '《母なる紋章》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm24-030'),
        officialUrl: officialPage('dm24-030'),
      },
      {
        name: '《英知と追撃の宝剣》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm11-s03'),
        officialUrl: officialPage('dm11-s03'),
      },
      {
        name: '《龍仙ロマネスク》と《母なる大地》または《母なる紋章》',
        initial: 'プレミアム殿堂コンビ → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂コンビ', '無制限'],
        imageUrl: officialImage('dm25-s04'),
        officialUrl: officialPage('dm25-s04'),
        images: [
          { src: officialImage('dm25-s04'), name: '龍仙ロマネスク' },
          { src: officialImage('dm10-036'), name: '母なる大地' },
          { src: officialImage('dm24-030'), name: '母なる紋章' },
        ],
      },
    ],
  },
  {
    slug: '2009-12-19',
    dateLabel: '2009年12月19日',
    title: '2009年12月19日 殿堂発表',
    description: '2009年12月19日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《呪紋の化身》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm07-019'),
        officialUrl: officialPage('dm07-019'),
      },
      {
        name: '《インフェルノ・ゲート》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm19-027'),
        officialUrl: officialPage('dm19-027'),
      },
      {
        name: '《ソウル・アドバンテージ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm28-027'),
        officialUrl: officialPage('dm28-027'),
      },
      {
        name: '《不滅の精霊パーフェクト・ギャラクシー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('28-SEC001'),
        officialUrl: officialPage('28-SEC001'),
      },
      {
        name: '《聖鎧亜キング・アルカディアス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm26-s03'),
        officialUrl: officialPage('dm26-s03'),
      },
      {
        name: '《インフェルノ・サイン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmc44-001'),
        officialUrl: officialPage('dmc44-001'),
      },
    ],
  },
  {
    slug: '2010-05-15',
    dateLabel: '2010年5月15日',
    title: '2010年5月15日 殿堂発表',
    description: '2010年5月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《聖鎧亜キング・アルカディアス》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm26-s03'),
        officialUrl: officialPage('dm26-s03'),
      },
      {
        name: '《パラダイス・アロマ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm16-042'),
        officialUrl: officialPage('dm16-042'),
      },
      {
        name: '《蒼狼の始祖アマテラス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm31-010'),
        officialUrl: officialPage('dm31-010'),
      },
      {
        name: '《龍仙ロマネスク》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm25-s04'),
        officialUrl: officialPage('dm25-s04'),
      },
      {
        name: '《エンペラー・キリコ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm32-s03'),
        officialUrl: officialPage('dm32-s03'),
      },
      {
        name: '《スパイラル・ゲート》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-086'),
        officialUrl: officialPage('dm01-086'),
      },
    ],
  },
  {
    slug: '2011-01-15',
    dateLabel: '2011年1月15日',
    title: '2011年1月15日 殿堂発表',
    description: '2011年1月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アクアン》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-010'),
        officialUrl: officialPage('dm04-010'),
      },
      {
        name: '《サイバー・ブレイン》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-052'),
        officialUrl: officialPage('dm01-052'),
      },
      {
        name: '《光牙忍ハヤブサマル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm29-037'),
        officialUrl: officialPage('dm29-037'),
      },
      {
        name: '《龍神ヘヴィ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc40-002'),
        officialUrl: officialPage('dmc40-002'),
      },
      {
        name: '《魔光蟲ヴィルジニア卿》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm30-044'),
        officialUrl: officialPage('dm30-044'),
      },
      {
        name: '《威牙の幻ハンゾウ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm29-003'),
        officialUrl: officialPage('dm29-003'),
      },
      {
        name: '《邪神M・ロマノフ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmc58-003'),
        officialUrl: officialPage('dmc58-003'),
      },
      {
        name: '《ラッキー・ダーツ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm12-007'),
        officialUrl: officialPage('dm12-007'),
      },
      {
        name: '《転生プログラム》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-021'),
        officialUrl: officialPage('dm10-021'),
      },
      {
        name: '《ハイドロ・ハリケーン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm04-011'),
        officialUrl: officialPage('dm04-011'),
      },
    ],
  },
  {
    slug: '2011-07-23',
    dateLabel: '2011年7月23日',
    title: '2011年7月23日 殿堂発表',
    description: '2011年7月23日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《時空の支配者ディアボロス Z》/《最凶の覚醒者デビル・ディアボロス Z》と《超次元バイス・ホール》',
        initial: '無制限 → プレミアム殿堂超次元コンビ',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dm39-s05a'),
        officialUrl: officialPage('dm39-s05a'),
        images: [
          { src: officialImage('dm39-s05a'), name: '時空の支配者ディアボロス Z / 最凶の覚醒者デビル・ディアボロス Z' },
          { src: officialImage('promoy10-019'), name: '超次元バイス・ホール' },
        ],
      },
      {
        name: '《超次元ドラヴィタ・ホール》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm37-023'),
        officialUrl: officialPage('dm37-023'),
      },
      {
        name: '《天雷の導士アヴァラルド公》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm28-043'),
        officialUrl: officialPage('dm28-043'),
      },
      {
        name: '《斬隠オロチ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm29-002'),
        officialUrl: officialPage('dm29-002'),
      },
      {
        name: '《再誕の社》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm36-069'),
        officialUrl: officialPage('dm36-069'),
      },
      {
        name: '《王機聖者ミル・アーマ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc52-004'),
        officialUrl: officialPage('dmc52-004'),
      },
      {
        name: '《ダンディ・ナスオ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm17-055'),
        officialUrl: officialPage('dm17-055'),
      },
    ],
  },
  {
    slug: '2012-03-15',
    dateLabel: '2012年3月15日',
    title: '2012年3月15日 殿堂発表',
    description: '2012年3月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《エンペラー・キリコ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm32-s03'),
        officialUrl: officialPage('dm32-s03'),
      },
      {
        name: '《邪神M・ロマノフ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmc58-003'),
        officialUrl: officialPage('dmc58-003'),
      },
      {
        name: '《母なる紋章》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm24-030'),
        officialUrl: officialPage('dm24-030'),
      },
      {
        name: '《カラフル・ダンス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm27-030'),
        officialUrl: officialPage('dm27-030'),
      },
    ],
  },
  {
    slug: '2012-08-11',
    dateLabel: '2012年8月11日',
    title: '2012年8月11日 殿堂発表',
    description: '2012年8月11日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ボルバルザーク・エクス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmx04-s05'),
        officialUrl: officialPage('dmx04-s05'),
      },
      {
        name: '《次元流の豪力》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-104'),
        officialUrl: officialPage('dmr01-104'),
      },
      {
        name: '《ビックリ・イリュージョン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm20-035'),
        officialUrl: officialPage('dm20-035'),
      },
      {
        name: '《偽りの名 ゾルゲ》と《紅蓮の怒 鬼流院 刃》',
        initial: '無制限 → プレミアム殿堂超次元コンビ',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dmr03-s05'),
        officialUrl: officialPage('dmr03-s05'),
        images: [
          { src: officialImage('dmr03-s05'), name: '偽りの名 ゾルゲ' },
          { src: officialImage('dmx06-v01a'), name: '紅蓮の怒 鬼流院 刃' },
        ],
      },
    ],
  },
  {
    slug: '2013-03-15',
    dateLabel: '2013年3月15日',
    title: '2013年3月15日 殿堂発表',
    description: '2013年3月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《セブンス・タワー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm14-109'),
        officialUrl: officialPage('dm14-109'),
      },
      {
        name: '《ミラクルとミステリーの扉》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm26-049'),
        officialUrl: officialPage('dm26-049'),
      },
    ],
  },
  {
    slug: '2013-06-22',
    dateLabel: '2013年6月22日',
    title: '2013年6月22日 殿堂発表',
    description: '2013年6月22日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ホーガン・ブラスター》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm39-026'),
        officialUrl: officialPage('dm39-026'),
      },
      {
        name: '《獰猛なる大地》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm27-012'),
        officialUrl: officialPage('dm27-012'),
      },
      {
        name: '《アクア・メルゲ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm37-010'),
        officialUrl: officialPage('dm37-010'),
      },
      {
        name: '《カモン・ピッピー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr03-026'),
        officialUrl: officialPage('dmr03-026'),
      },
    ],
  },
  {
    slug: '2014-03-15',
    dateLabel: '2014年3月15日',
    title: '2014年3月15日 殿堂発表',
    description: '2014年3月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《超次元バイス・ホール》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('promoy10-019'),
        officialUrl: officialPage('promoy10-019'),
      },
      {
        name: '《ミラクルとミステリーの扉》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm26-049'),
        officialUrl: officialPage('dm26-049'),
      },
      {
        name: '《ガチンコ・ルーレット》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr07-035'),
        officialUrl: officialPage('dmr07-035'),
      },
      {
        name: '《ポジトロン・サイン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm32-015'),
        officialUrl: officialPage('dm32-015'),
      },
      {
        name: '《希望の絆 鬼修羅》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr08-s05'),
        officialUrl: officialPage('dmr08-s05'),
      },
      {
        name: '《パーロックのミラクルフィーバー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-021'),
        officialUrl: officialPage('dmr01-021'),
      },
      {
        name: '《盗掘人形モールス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm16-027'),
        officialUrl: officialPage('dm16-027'),
      },
      {
        name: '《時空の支配者ディアボロス Z》/《最凶の覚醒者デビル・ディアボロス Z》と《超次元バイス・ホール》',
        initial: 'プレミアム殿堂超次元コンビ → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dm39-s05a'),
        officialUrl: officialPage('dm39-s05a'),
        images: [
          { src: officialImage('dm39-s05a'), name: '時空の支配者ディアボロス Z / 最凶の覚醒者デビル・ディアボロス Z' },
          { src: officialImage('promoy10-019'), name: '超次元バイス・ホール' },
        ],
      },
    ],
  },
  {
    slug: '2014-05-24',
    dateLabel: '2014年5月24日',
    title: '2014年5月24日 殿堂発表',
    description: '2014年5月24日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《勝利宣言 鬼丸「覇」》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr06-v01'),
        officialUrl: officialPage('dmr06-v01'),
      },
      {
        name: '《予言者ローラン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm36-012'),
        officialUrl: officialPage('dm36-012'),
      },
      {
        name: '《疾封怒闘 キューブリック》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr08s-005'),
        officialUrl: officialPage('dmr08s-005'),
      },
      {
        name: '《デビル・ドレーン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm03-014'),
        officialUrl: officialPage('dm03-014'),
      },
      {
        name: '《鎧亜の咆哮キリュー・ジルヴェス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm25-035'),
        officialUrl: officialPage('dm25-035'),
      },
      {
        name: '《陰陽の舞》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm39-034'),
        officialUrl: officialPage('dm39-034'),
      },
    ],
  },
  {
    slug: '2015-03-14',
    dateLabel: '2015年3月14日',
    title: '2015年3月14日 殿堂発表',
    description: '2015年3月14日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《蒼狼の始祖アマテラス》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm31-010'),
        officialUrl: officialPage('dm31-010'),
      },
      {
        name: '《超次元ホワイトグリーン・ホール》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr02-031'),
        officialUrl: officialPage('dmr02-031'),
      },
      {
        name: '《ミステリー・キューブ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr09-039'),
        officialUrl: officialPage('dmr09-039'),
      },
    ],
  },
  {
    slug: '2015-06-15',
    dateLabel: '2015年6月15日',
    title: '2015年6月15日 殿堂発表',
    description: '2015年6月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《魔天降臨》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-026'),
        officialUrl: officialPage('dm10-026'),
      },
      {
        name: '《鎧亜戦隊ディス・マジシャン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr03-019'),
        officialUrl: officialPage('dmr03-019'),
      },
      {
        name: '《ヒラメキ・プログラム》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr05-022'),
        officialUrl: officialPage('dmr05-022'),
      },
      {
        name: '《暴龍警報》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr14-051'),
        officialUrl: officialPage('dmr14-051'),
      },
    ],
  },
  {
    slug: '2015-09-19',
    dateLabel: '2015年9月19日',
    title: '2015年9月19日 殿堂発表',
    description: '2015年9月19日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ボルメテウス・サファイア・ドラゴン》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc27-004'),
        officialUrl: officialPage('dmc27-004'),
      },
    ],
  },
  {
    slug: '2015-12-15',
    dateLabel: '2015年12月15日',
    title: '2015年12月15日 殿堂発表',
    description: '2015年12月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《禁断 ～封印されしX～》/《伝説の禁断 ドキンダムX》',
        initial: '登場と同時に殿堂入り',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmr19-fl01a'),
        officialUrl: officialPage('dmr19-fl01'),
        images: [
          { src: officialImage('dmr19-fl01a'), name: '禁断 ～封印されしX～' },
          { src: officialImage('dmr19-fl01b'), name: '伝説の禁断 ドキンダムX' },
        ],
      },
    ],
  },
  {
    slug: '2016-02-01',
    dateLabel: '2016年2月1日',
    title: '2016年2月1日 殿堂発表',
    description: '2016年2月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《雷鳴の守護者ミスト・リエス》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('promoy1-019'),
        officialUrl: officialPage('promoy1-019'),
      },
      {
        name: '《ディープ・オペレーション》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm02-026'),
        officialUrl: officialPage('dm02-026'),
      },
      {
        name: '《パシフィック・チャンピオン》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm13-009'),
        officialUrl: officialPage('dm13-009'),
      },
      {
        name: '《予言者ローラン》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm36-012'),
        officialUrl: officialPage('dm36-012'),
      },
      {
        name: '《炎槍と水剣の裁》',
        initial: 'プレミアム殿堂 → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '無制限'],
        imageUrl: officialImage('dm13-031'),
        officialUrl: officialPage('dm13-031'),
      },
      {
        name: '《龍神ヘヴィ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc40-002'),
        officialUrl: officialPage('dmc40-002'),
      },
      {
        name: '《アクア・ハルカス》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-080'),
        officialUrl: officialPage('dm01-080'),
      },
      {
        name: '《凶星王ダーク・ヒドラ》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc38-009'),
        officialUrl: officialPage('dmc38-009'),
      },
    ],
  },
  {
    slug: '2016-02-28',
    dateLabel: '2016年2月28日',
    title: '2016年2月28日 殿堂発表',
    description: '2016年2月28日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《転生プログラム》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm10-021'),
        officialUrl: officialPage('dm10-021'),
      },
      {
        name: '《鎧亜戦隊ディス・マジシャン》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr03-019'),
        officialUrl: officialPage('dmr03-019'),
      },
      {
        name: '《無双恐皇ガラムタ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm13-s05'),
        officialUrl: officialPage('dm13-s05'),
      },
      {
        name: '《奇跡の精霊ミルザム》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm29-s01'),
        officialUrl: officialPage('dm29-s01'),
      },
      {
        name: '《極魔王殿 ウェルカム・ヘル》/《極・魔壊王 デスゴロス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr16g-v01a'),
        officialUrl: officialPage('dmr16g-v01'),
        images: [
          { src: officialImage('dmr16g-v01a'), name: '極魔王殿 ウェルカム・ヘル' },
          { src: officialImage('dmr16g-v01b'), name: '極・魔壊王 デスゴロス' },
        ],
      },
    ],
  },
  {
    slug: '2016-09-15',
    dateLabel: '2016年9月15日',
    title: '2016年9月15日 殿堂発表',
    description: '2016年9月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《王機聖者ミル・アーマ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc52-004'),
        officialUrl: officialPage('dmc52-004'),
      },
      {
        name: '《次元流の豪力》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-104'),
        officialUrl: officialPage('dmr01-104'),
      },
      {
        name: '《邪帝斧 ボアロアックス》/《邪帝遺跡 ボアロパゴス》/《我臥牙 ヴェロキボアロス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmx18-016a'),
        officialUrl: officialPage('dmx18-016'),
        images: [
          { src: officialImage('dmx18-016a'), name: '邪帝斧 ボアロアックス' },
          { src: officialImage('dmx18-016b'), name: '邪帝遺跡 ボアロパゴス' },
          { src: officialImage('dmx18-016c'), name: '我臥牙 ヴェロキボアロス' },
        ],
      },
      {
        name: '《フェアリー・ギフト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm14-069'),
        officialUrl: officialPage('dm14-069'),
      },
      {
        name: '《フォース・アゲイン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm31-025'),
        officialUrl: officialPage('dm31-025'),
      },
    ],
  },
  {
    slug: '2016-12-16',
    dateLabel: '2016年12月16日',
    title: '2016年12月16日 殿堂発表',
    description: '2016年12月16日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《FORBIDDEN STAR ～世界最後の日～》/《終焉の禁断 ドルマゲドンX》',
        initial: '登場と同時に殿堂入り',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmr23-ffl01a'),
        officialUrl: officialPage('dmr23-ffl01'),
        images: [
          { src: officialImage('dmr23-ffl01a'), name: 'FORBIDDEN STAR ～世界最後の日～' },
          { src: officialImage('dmr23-ffl01b'), name: '終焉の禁断 ドルマゲドンX' },
        ],
      },
    ],
  },
  {
    slug: '2017-01-30',
    dateLabel: '2017年1月30日',
    title: '2017年1月30日 殿堂発表',
    description: '2017年1月30日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《不滅の精霊パーフェクト・ギャラクシー》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('28-SEC001'),
        officialUrl: officialPage('28-SEC001'),
      },
      {
        name: '《偽りの名 ゾルゲ》と《紅蓮の怒 鬼流院 刃》',
        initial: 'プレミアム殿堂超次元コンビ → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dmr03-s05'),
        officialUrl: officialPage('dmr03-s05'),
        images: [
          { src: officialImage('dmr03-s05'), name: '偽りの名 ゾルゲ' },
          { src: officialImage('dmx06-v01a'), name: '紅蓮の怒 鬼流院 刃' },
        ],
      },
    ],
  },
  {
    slug: '2017-02-26',
    dateLabel: '2017年2月26日',
    title: '2017年2月26日 殿堂発表',
    description: '2017年2月26日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《天雷王機ジョバンニX世》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dm36-015'),
        officialUrl: officialPage('dm36-015'),
      },
      {
        name: '《奇跡の精霊ミルザム》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm29-s01'),
        officialUrl: officialPage('dm29-s01'),
      },
      {
        name: '《絶叫の悪魔龍 イーヴィル・ヒート》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr21-010'),
        officialUrl: officialPage('dmr21-010'),
      },
      {
        name: '《蛇手の親分ゴエモンキー！》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm36-039'),
        officialUrl: officialPage('dm36-039'),
      },
      {
        name: '《常勝ディス・オプティマス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr02-s05'),
        officialUrl: officialPage('dmr02-s05'),
      },
      {
        name: '《復讐 ブラックサイコ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr17-005'),
        officialUrl: officialPage('dmr17-005'),
      },
      {
        name: '《メガ・マナロック・ドラゴン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr17-s08'),
        officialUrl: officialPage('dmr17-s08'),
      },
    ],
  },
  {
    slug: '2017-07-08',
    dateLabel: '2017年7月8日',
    title: '2017年7月8日 殿堂発表',
    description: '2017年7月8日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アラゴト・ムスビ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm37-051'),
        officialUrl: officialPage('dm37-051'),
      },
      {
        name: '《S級原始 サンマッド》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr19-s09'),
        officialUrl: officialPage('dmr19-s09'),
      },
      {
        name: '《スクランブル・チェンジ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr22-019'),
        officialUrl: officialPage('dmr22-019'),
      },
      {
        name: '《大勇者「鎖風車」》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-032'),
        officialUrl: officialPage('dm10-032'),
      },
      {
        name: '《魔龍バベルギヌス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm22-003'),
        officialUrl: officialPage('dm22-003'),
      },
      {
        name: '《目的不明の作戦》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmx21-066'),
        officialUrl: officialPage('dmx21-066'),
      },
    ],
  },
  {
    slug: '2018-01-29',
    dateLabel: '2018年1月29日',
    title: '2018年1月29日 殿堂発表',
    description: '2018年1月29日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《天雷の導士アヴァラルド公》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm28-043'),
        officialUrl: officialPage('dm28-043'),
      },
      {
        name: '《龍仙ロマネスク》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm25-s04'),
        officialUrl: officialPage('dm25-s04'),
      },
    ],
  },
  {
    slug: '2018-03-01',
    dateLabel: '2018年3月1日',
    title: '2018年3月1日 殿堂発表',
    description: '2018年3月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神》と《超戦龍覇 モルトNEXT》',
        initial: '無制限 → プレミアム殿堂超次元コンビ',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dmx18-001a'),
        officialUrl: officialPage('dmx18-001'),
        images: [
          { src: officialImage('dmx18-001a'), name: '爆熱剣 バトライ刃' },
          { src: officialImage('dmx18-001b'), name: '爆熱天守 バトライ閣' },
          { src: officialImage('dmx18-001c'), name: '爆熱DX バトライ武神' },
          { src: officialImage('dmr16g-vv01'), name: '超戦龍覇 モルトNEXT' },
        ],
      },
      {
        name: '《ベイB ジャック》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr23-005'),
        officialUrl: officialPage('dmr23-005'),
      },
      {
        name: '《裏切りの魔狼月下城》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr22-017'),
        officialUrl: officialPage('dmr22-017'),
      },
      {
        name: '《超次元ガロウズ・ホール》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-050'),
        officialUrl: officialPage('dmr01-050'),
      },
      {
        name: '《破界秘伝ナッシング・ゼロ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmx13-013'),
        officialUrl: officialPage('dmx13-013'),
      },
      {
        name: '《真・龍覇 ヘブンズロージア》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr16s-007'),
        officialUrl: officialPage('dmr16s-007'),
      },
      {
        name: '《単騎連射 マグナム》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmd27-003'),
        officialUrl: officialPage('dmd27-003'),
      },
      {
        name: '《音精 ラフルル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmx23-014'),
        officialUrl: officialPage('dmx23-014'),
      },
      {
        name: '《龍素知新》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr16g-009'),
        officialUrl: officialPage('dmr16g-009'),
      },
    ],
  },
  {
    slug: '2018-07-14',
    dateLabel: '2018年7月14日',
    title: '2018年7月14日 殿堂発表',
    description: '2018年7月14日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《勝利のアパッチ・ウララー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr04-032'),
        officialUrl: officialPage('dmr04-032'),
      },
      {
        name: '《次元の霊峰》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm11-055'),
        officialUrl: officialPage('dm11-055'),
      },
      {
        name: '《ゼロの裏技ニヤリー・ゲット》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr10-039'),
        officialUrl: officialPage('dmr10-039'),
      },
      {
        name: '《プラチナ・ワルスラS》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr23-002'),
        officialUrl: officialPage('dmr23-002'),
      },
    ],
  },
  {
    slug: '2019-01-21',
    dateLabel: '2019年1月21日',
    title: '2019年1月21日 殿堂発表',
    description: '2019年1月21日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アストラル・リーフ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-002'),
        officialUrl: officialPage('dm04-002'),
      },
      {
        name: '《威牙の幻ハンゾウ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm29-003'),
        officialUrl: officialPage('dm29-003'),
      },
      {
        name: '《ミステリー・キューブ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr09-039'),
        officialUrl: officialPage('dmr09-039'),
      },
    ],
  },
  {
    slug: '2019-03-01',
    dateLabel: '2019年3月1日',
    title: '2019年3月1日 殿堂発表',
    description: '2019年3月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《蒼き団長 ドギラゴン剣》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr21-l02'),
        officialUrl: officialPage('dmr21-l02'),
      },
      {
        name: '《時の法皇 ミラダンテXII》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr22-l03'),
        officialUrl: officialPage('dmr22-l03'),
      },
      {
        name: '《ドリル・スコール》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm16-051'),
        officialUrl: officialPage('dm16-051'),
      },
      {
        name: '《黒神龍ブライゼナーガ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-s04'),
        officialUrl: officialPage('dm10-s04'),
      },
      {
        name: '《瞬封の使徒サグラダ・ファミリア》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr07-022'),
        officialUrl: officialPage('dmr07-022'),
      },
      {
        name: '《ヴォルグ・サンダー》/《雷獣ヴォルグ・ティーガー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr02-v01a'),
        officialUrl: officialPage('dmr02-v01'),
        images: [
          { src: officialImage('dmr02-v01a'), name: 'ヴォルグ・サンダー' },
          { src: officialImage('dmr02-v01b'), name: '雷獣ヴォルグ・ティーガー' },
        ],
      },
    ],
  },
  {
    slug: '2019-07-01',
    dateLabel: '2019年7月1日',
    title: '2019年7月1日 殿堂発表',
    description: '2019年7月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ヴォルグ・サンダー》/《雷獣ヴォルグ・ティーガー》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr02-v01a'),
        officialUrl: officialPage('dmr02-v01'),
        images: [
          { src: officialImage('dmr02-v01a'), name: 'ヴォルグ・サンダー' },
          { src: officialImage('dmr02-v01b'), name: '雷獣ヴォルグ・ティーガー' },
        ],
      },
      {
        name: '《ヒラメキ・プログラム》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr05-022'),
        officialUrl: officialPage('dmr05-022'),
      },
      {
        name: '《セイレーン・コンチェルト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-048'),
        officialUrl: officialPage('dm10-048'),
      },
      {
        name: '《“轟轟轟”ブランド》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp06-m01'),
        officialUrl: officialPage('dmrp06-m01'),
      },
      {
        name: '《ガヨウ神》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmrp05-s01'),
        officialUrl: officialPage('dmrp05-s01'),
      },
    ],
  },
  {
    slug: '2019-12-20',
    dateLabel: '2019年12月20日',
    title: '2019年12月20日 殿堂発表',
    description: '2019年12月20日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《滅亡の起源 零無》/《零龍》',
        initial: '登場と同時に殿堂入り',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmrp12-mz1a'),
        officialUrl: officialPage('dmrp12-mz1'),
        images: [
          { src: officialImage('dmrp12-mz1a'), name: '滅亡の起源 零無' },
          { src: officialImage('dmrp12-mz1b'), name: '零龍' },
        ],
      },
    ],
  },
  {
    slug: '2020-01-01',
    dateLabel: '2020年1月1日',
    title: '2020年1月1日 殿堂発表',
    description: '2020年1月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《アクア・メルゲ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm37-010'),
        officialUrl: officialPage('dm37-010'),
      },
      {
        name: '《音精 ラフルル》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmx23-014'),
        officialUrl: officialPage('dmx23-014'),
      },
      {
        name: '《BAKUOOON・ミッツァイル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp09-s09'),
        officialUrl: officialPage('dmrp09-s09'),
      },
      {
        name: '《機術士ディール／「本日のラッキーナンバー！」》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp05-003'),
        officialUrl: officialPage('dmrp05-003'),
      },
      {
        name: '《Dの牢閣 メメント守神宮》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr23-030'),
        officialUrl: officialPage('dmr23-030'),
      },
      {
        name: '《禁断機関 VV-8》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr22-l01'),
        officialUrl: officialPage('dmr22-l01'),
      },
      {
        name: '《バロン・ゴーヤマ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm27-004'),
        officialUrl: officialPage('dm27-004'),
      },
      {
        name: '《侵革目 パラスラプト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr20-008'),
        officialUrl: officialPage('dmr20-008'),
      },
      {
        name: '《勝利のアパッチ・ウララー》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr04-032'),
        officialUrl: officialPage('dmr04-032'),
      },
      {
        name: '《魔光蟲ヴィルジニア卿》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm30-044'),
        officialUrl: officialPage('dm30-044'),
      },
      {
        name: '《希望の絆 鬼修羅》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr08-s05'),
        officialUrl: officialPage('dmr08-s05'),
      },
      {
        name: '《セブンス・タワー》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm14-109'),
        officialUrl: officialPage('dm14-109'),
      },
      {
        name: '《超次元ドラヴィタ・ホール》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm37-023'),
        officialUrl: officialPage('dm37-023'),
      },
    ],
  },
  {
    slug: '2020-01-19',
    dateLabel: '2020年1月19日',
    title: '2020年1月19日 殿堂発表',
    description: '2020年1月19日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《緊急プレミアム殿堂》',
        initial: '登場と同時にプレミアム殿堂',
        description: '',
        history: ['プレミアム殿堂'],
        imageUrl: officialImage('dmex08-169'),
        officialUrl: officialPage('dmex08-169'),
      },
    ],
  },
  {
    slug: '2020-07-01',
    dateLabel: '2020年7月1日',
    title: '2020年7月1日 殿堂発表',
    description: '2020年7月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ヨミジ 丁-二式》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp12-022'),
        officialUrl: officialPage('dmrp12-022'),
      },
      {
        name: '《マリゴルドIII》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp11-028'),
        officialUrl: officialPage('dmrp11-028'),
      },
      {
        name: '《MEGATOON・ドッカンデイヤー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp10-010'),
        officialUrl: officialPage('dmrp10-010'),
      },
      {
        name: '《腐敗勇騎ドルマークス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmx09-030'),
        officialUrl: officialPage('dmx09-030'),
      },
      {
        name: '《熱き侵略 レッドゾーンZ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmd27-014'),
        officialUrl: officialPage('dmd27-014'),
      },
      {
        name: '《怨念怪人ギャスカ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm14-055'),
        officialUrl: officialPage('dm14-055'),
      },
      {
        name: '《魂と記憶の盾》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm11-004'),
        officialUrl: officialPage('dm11-004'),
      },
      {
        name: '《ガチンコ・ルーレット》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr07-035'),
        officialUrl: officialPage('dmr07-035'),
      },
      {
        name: '《真・龍覇 ヘブンズロージア》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr16s-007'),
        officialUrl: officialPage('dmr16s-007'),
      },
    ],
  },
  {
    slug: '2020-12-18',
    dateLabel: '2020年12月18日',
    title: '2020年12月18日 殿堂発表',
    description: '2020年12月18日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ヘブンズ・フォース》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr21-062'),
        officialUrl: officialPage('dmr21-062'),
      },
      {
        name: '《爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmx18-001a'),
        officialUrl: officialPage('dmx18-001'),
        images: [
          { src: officialImage('dmx18-001a'), name: '爆熱剣 バトライ刃' },
          { src: officialImage('dmx18-001b'), name: '爆熱天守 バトライ閣' },
          { src: officialImage('dmx18-001c'), name: '爆熱DX バトライ武神' },
        ],
      },
      {
        name: '《凄惨なる牙 パラノーマル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr10-013'),
        officialUrl: officialPage('dmr10-013'),
      },
      {
        name: '《魔導管理室 カリヤドネ／ハーミット・サークル》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp11-s04a'),
        officialUrl: officialPage('dmrp11-s04'),
      },
      {
        name: '《生命と大地と轟破の決断》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp11-s12'),
        officialUrl: officialPage('dmrp11-s12'),
      },
      {
        name: '《ジョット・ガン・ジョラゴン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp05-m02'),
        officialUrl: officialPage('dmrp05-m02'),
      },
      {
        name: '《海底鬼面城》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm30-026'),
        officialUrl: officialPage('dm30-026'),
      },
      {
        name: '《爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神》と《超戦龍覇 モルトNEXT》',
        initial: 'プレミアム殿堂超次元コンビ → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂超次元コンビ', '無制限'],
        imageUrl: officialImage('dmx18-001a'),
        officialUrl: officialPage('dmx18-001'),
        images: [
          { src: officialImage('dmx18-001a'), name: '爆熱剣 バトライ刃' },
          { src: officialImage('dmx18-001b'), name: '爆熱天守 バトライ閣' },
          { src: officialImage('dmx18-001c'), name: '爆熱DX バトライ武神' },
          { src: officialImage('dmr16g-vv01'), name: '超戦龍覇 モルトNEXT' },
        ],
      },
      {
        name: '《超次元ホワイトグリーン・ホール》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr02-031'),
        officialUrl: officialPage('dmr02-031'),
      },
      {
        name: '《超次元ガロウズ・ホール》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-050'),
        officialUrl: officialPage('dmr01-050'),
      },
      {
        name: '《ボルメテウス・サファイア・ドラゴン》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc27-004'),
        officialUrl: officialPage('dmc27-004'),
      },
    ],
  },
  {
    slug: '2021-07-01',
    dateLabel: '2021年7月1日',
    title: '2021年7月1日 殿堂発表',
    description: '2021年7月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《レアリティ・レジスタンス》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmx22b-136'),
        officialUrl: officialPage('dmx22b-136'),
      },
      {
        name: '《裏切りの魔狼月下城》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmr22-017'),
        officialUrl: officialPage('dmr22-017'),
      },
      {
        name: '《暗黒鎧 ダースシスK》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr21-003'),
        officialUrl: officialPage('dmr21-003'),
      },
      {
        name: '《不敵怪人アンダケイン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp13-018'),
        officialUrl: officialPage('dmrp13-018'),
      },
      {
        name: '《サイバー・I・チョイス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr17-017'),
        officialUrl: officialPage('dmr17-017'),
      },
      {
        name: '《サイバー・ブレイン》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-052'),
        officialUrl: officialPage('dm01-052'),
      },
    ],
  },
  {
    slug: '2022-01-01',
    dateLabel: '2022年1月1日',
    title: '2022年1月1日 殿堂発表',
    description: '2022年1月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《希望のジョー星》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmex12-022'),
        officialUrl: officialPage('dmex12-022'),
      },
      {
        name: '《“龍装”チュリス》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp04m-016'),
        officialUrl: officialPage('dmrp04m-016'),
      },
      {
        name: '《エンペラー・キリコ》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm32-s03'),
        officialUrl: officialPage('dm32-s03'),
      },
      {
        name: '《絶叫の悪魔龍 イーヴィル・ヒート》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr21-010'),
        officialUrl: officialPage('dmr21-010'),
      },
    ],
  },
  {
    slug: '2022-07-01',
    dateLabel: '2022年7月1日',
    title: '2022年7月1日 殿堂発表',
    description: '2022年7月1日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《禁断 ～封印されしX～》/《伝説の禁断 ドキンダムX》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmr19-fl01a'),
        officialUrl: officialPage('dmr19-fl01'),
        images: [
          { src: officialImage('dmr19-fl01a'), name: '禁断 ～封印されしX～' },
          { src: officialImage('dmr19-fl01b'), name: '伝説の禁断 ドキンダムX' },
        ],
      },
      {
        name: '《FORBIDDEN STAR ～世界最後の日～》/《終焉の禁断 ドルマゲドンX》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmr23-ffl01a'),
        officialUrl: officialPage('dmr23-ffl01'),
        images: [
          { src: officialImage('dmr23-ffl01a'), name: 'FORBIDDEN STAR ～世界最後の日～' },
          { src: officialImage('dmr23-ffl01b'), name: '終焉の禁断 ドルマゲドンX' },
        ],
      },
      {
        name: '《滅亡の起源 零無》/《零龍》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['殿堂入り', '無制限'],
        imageUrl: officialImage('dmrp12-mz1a'),
        officialUrl: officialPage('dmrp12-mz1'),
        images: [
          { src: officialImage('dmrp12-mz1a'), name: '滅亡の起源 零無' },
          { src: officialImage('dmrp12-mz1b'), name: '零龍' },
        ],
      },
      {
        name: '《サイバー・ブレイン》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-052'),
        officialUrl: officialPage('dm01-052'),
      },
      {
        name: '《プラチナ・ワルスラS》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr23-002'),
        officialUrl: officialPage('dmr23-002'),
      },
      {
        name: '《パーロックのミラクルフィーバー》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-021'),
        officialUrl: officialPage('dmr01-021'),
      },
      {
        name: '《パラダイス・アロマ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm16-042'),
        officialUrl: officialPage('dm16-042'),
      },
      {
        name: '《凶星王ダーク・ヒドラ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmc38-009'),
        officialUrl: officialPage('dmc38-009'),
      },
      {
        name: '《スパイラル・ゲート》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm01-086'),
        officialUrl: officialPage('dm01-086'),
      },
      {
        name: '《カモン・ピッピー》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr03-026'),
        officialUrl: officialPage('dmr03-026'),
      },
      {
        name: '《鎧亜の咆哮キリュー・ジルヴェス》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm25-035'),
        officialUrl: officialPage('dm25-035'),
      },
      {
        name: '《破界秘伝ナッシング・ゼロ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmx13-013'),
        officialUrl: officialPage('dmx13-013'),
      },
      {
        name: '《極魔王殿 ウェルカム・ヘル》/《極・魔壊王 デスゴロス》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr16g-v01a'),
        officialUrl: officialPage('dmr16g-v01'),
        images: [
          { src: officialImage('dmr16g-v01a'), name: '極魔王殿 ウェルカム・ヘル' },
          { src: officialImage('dmr16g-v01b'), name: '極・魔壊王 デスゴロス' },
        ],
      },
      {
        name: '《獰猛なる大地》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm27-012'),
        officialUrl: officialPage('dm27-012'),
      },
      {
        name: '《ガヨウ神》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmrp05-s01'),
        officialUrl: officialPage('dmrp05-s01'),
      },
      {
        name: '《次元流の豪力》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-104'),
        officialUrl: officialPage('dmr01-104'),
      },
      {
        name: '《超次元バイス・ホール》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('promoy10-019'),
        officialUrl: officialPage('promoy10-019'),
      },
      {
        name: '《アクアン》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-010'),
        officialUrl: officialPage('dm04-010'),
      },
      {
        name: '《ミラクルとミステリーの扉》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dm26-049'),
        officialUrl: officialPage('dm26-049'),
      },
      {
        name: '《邪神M・ロマノフ》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmc58-003'),
        officialUrl: officialPage('dmc58-003'),
      },
    ],
  },
  {
    slug: '2022-08-15',
    dateLabel: '2022年8月15日',
    title: '2022年8月15日 殿堂発表',
    description: '2022年8月15日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《禁断英雄 モモキングダムX》と《未来王龍 モモキングJO》',
        initial: '無制限 → プレミアム殿堂コンビ',
        description: '',
        history: ['無制限', 'プレミアム殿堂コンビ'],
        imageUrl: officialImage('dmrp19-km1'),
        officialUrl: officialPage('dmrp19-km1'),
        images: [
          { src: officialImage('dmrp19-km1'), name: '禁断英雄 モモキングダムX' },
          { src: officialImage('dmrp20-km1'), name: '未来王龍 モモキングJO' },
        ],
      },
      {
        name: '《爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmx18-001a'),
        officialUrl: officialPage('dmx18-001'),
        images: [
          { src: officialImage('dmx18-001a'), name: '爆熱剣 バトライ刃' },
          { src: officialImage('dmx18-001b'), name: '爆熱天守 バトライ閣' },
          { src: officialImage('dmx18-001c'), name: '爆熱DX バトライ武神' },
        ],
      },
      {
        name: '《竜魔神王バルカディア・NEX》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmx12b-026'),
        officialUrl: officialPage('dmx12b-026'),
      },
      {
        name: '《超七極 Gio／巨大設計図》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex17-105a'),
        officialUrl: officialPage('dmex17-105'),
      },
      {
        name: '《月下旋壊 ド・リュミーズ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex17-054'),
        officialUrl: officialPage('dmex17-054'),
      },
      {
        name: '《樹食の超人》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex14-019'),
        officialUrl: officialPage('dmex14-019'),
      },
    ],
  },
  {
    slug: '2023-03-20',
    dateLabel: '2023年3月20日',
    title: '2023年3月20日 殿堂発表',
    description: '2023年3月20日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ダンディ・ナスオ》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm17-055'),
        officialUrl: officialPage('dm17-055'),
      },
      {
        name: '《希望のジョー星》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmex12-022'),
        officialUrl: officialPage('dmex12-022'),
      },
      {
        name: '《生命と大地と轟破の決断》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp11-s12'),
        officialUrl: officialPage('dmrp11-s12'),
      },
      {
        name: '《暗黒鎧 ザロスト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmr18-035'),
        officialUrl: officialPage('dmr18-035'),
      },
      {
        name: '《ガル・ラガンザーク》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex16-061'),
        officialUrl: officialPage('dmex16-061'),
      },
      {
        name: '《一なる部隊 イワシン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp03-036'),
        officialUrl: officialPage('dmrp03-036'),
      },
      {
        name: '《英知と追撃の宝剣》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm11-s03'),
        officialUrl: officialPage('dm11-s03'),
      },
      {
        name: '《スクランブル・チェンジ》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr22-019'),
        officialUrl: officialPage('dmr22-019'),
      },
    ],
  },
  {
    slug: '2023-08-11',
    dateLabel: '2023年8月11日',
    title: '2023年8月11日 殿堂発表',
    description: '2023年8月11日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《神の試練》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmex15-b014'),
        officialUrl: officialPage('dmex15-b014'),
      },
      {
        name: '《蝕王の晩餐》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp03-020'),
        officialUrl: officialPage('dmrp03-020'),
      },
      {
        name: '《絶望神サガ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm22ex2-021'),
        officialUrl: officialPage('dm22ex2-021'),
      },
      {
        name: '《勝利宣言 鬼丸「覇」》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr06-v01'),
        officialUrl: officialPage('dmr06-v01'),
      },
    ],
  },
  {
    slug: '2024-03-11',
    dateLabel: '2024年3月11日',
    title: '2024年3月11日 殿堂発表',
    description: '2024年3月11日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《機術士ディール／「本日のラッキーナンバー！」》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp05-003a'),
        officialUrl: officialPage('dmrp05-003'),
      },
      {
        name: '《神の試練》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dmex15-b014'),
        officialUrl: officialPage('dmex15-b014'),
      },
      {
        name: '《「無月」の頂 ＄スザーク＄》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm22ex1-008'),
        officialUrl: officialPage('dm22ex1-008'),
      },
      {
        name: '《超神羅星アポロヌス・ドラゲリオン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex17-013'),
        officialUrl: officialPage('dmex17-013'),
      },
      {
        name: '《幻緑の双月／母なる星域》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex04-052a'),
        officialUrl: officialPage('dmex04-052'),
      },
      {
        name: '《天命龍装 ホーリーエンド／ナウ・オア・ネバー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp12-s01a'),
        officialUrl: officialPage('dmrp12-s01'),
      },
      {
        name: '《次元流の豪力》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr01-104'),
        officialUrl: officialPage('dmr01-104'),
      },
      {
        name: '《超次元バイス・ホール》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('promoy10-019'),
        officialUrl: officialPage('promoy10-019'),
      },
      {
        name: '《ボルバルザーク・エクス》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmx04-s05'),
        officialUrl: officialPage('dmx04-s05'),
      },
    ],
  },
  {
    slug: '2024-08-10',
    dateLabel: '2024年8月10日',
    title: '2024年8月10日 殿堂発表',
    description: '2024年8月10日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ゼロの裏技ニヤリー・ゲット》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dmr10-039'),
        officialUrl: officialPage('dmr10-039'),
      },
    ],
  },
  {
    slug: '2024-08-17',
    dateLabel: '2024年8月17日',
    title: '2024年8月17日 殿堂発表',
    description: '2024年8月17日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《緊急再誕》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-015'),
        officialUrl: officialPage('dm10-015'),
      },
      {
        name: '《邪幽 ジャガイスト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm23ex1-004'),
        officialUrl: officialPage('dm23ex1-004'),
      },
      {
        name: '《瞬閃と疾駆と双撃の決断》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmrp11-007'),
        officialUrl: officialPage('dmrp11-007'),
      },
    ],
  },
  {
    slug: '2025-03-10',
    dateLabel: '2025年3月10日',
    title: '2025年3月10日 殿堂発表',
    description: '2025年3月10日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《困惑の影トラブル・アルケミスト》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm10-025'),
        officialUrl: officialPage('dm10-025'),
      },
      {
        name: '《DARK MATERIAL COMPLEX》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm23rp4-S02'),
        officialUrl: officialPage('dm23rp4-S02'),
      },
      {
        name: '《マーシャル・クイーン》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm16-009'),
        officialUrl: officialPage('dm16-009'),
      },
      {
        name: '《雷炎翔鎧バルピアレスク》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm23rp2-S06'),
        officialUrl: officialPage('dm23rp2-S06'),
      },
      {
        name: '《アクアン》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm04-010'),
        officialUrl: officialPage('dm04-010'),
      },
    ],
  },
  {
    slug: '2025-08-12',
    dateLabel: '2025年8月12日',
    title: '2025年8月12日 殿堂発表',
    description: '2025年8月12日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ツタンメカーネン》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmrp09-029'),
        officialUrl: officialPage('dmrp09-029'),
      },
      {
        name: '《der\'Zen Mondo／♪必殺で つわものどもが 夢の跡》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dm23rp1-S3a'),
        officialUrl: officialPage('dm23rp1-S3'),
      },
      {
        name: '《フォース・アゲイン》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm31-025'),
        officialUrl: officialPage('dm31-025'),
      },
      {
        name: '《雷炎翔鎧バルピアレスク》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm23rp2-S06'),
        officialUrl: officialPage('dm23rp2-S06'),
      },
      {
        name: '《逆転の影ガレック》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm24rp3-019'),
        officialUrl: officialPage('dm24rp3-019'),
      },
      {
        name: '《死神覇王 ブラックXENARCH》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm24rp2-S05'),
        officialUrl: officialPage('dm24rp2-S05'),
      },
      {
        name: '《頂上混成 BAKUONSOOO8th》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm24ex2-017'),
        officialUrl: officialPage('dm24ex2-017'),
      },
      {
        name: '《アリスの突撃インタビュー》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm24ex1-033'),
        officialUrl: officialPage('dm24ex1-033'),
      },
      {
        name: '《爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神》',
        initial: 'プレミアム殿堂 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂', '殿堂入り'],
        imageUrl: officialImage('dmx18-001a'),
        officialUrl: officialPage('dmx18-001'),
        images: [
          { src: officialImage('dmx18-001a'), name: '爆熱剣 バトライ刃' },
          { src: officialImage('dmx18-001b'), name: '爆熱天守 バトライ閣' },
          { src: officialImage('dmx18-001c'), name: '爆熱DX バトライ武神' },
        ],
      },
    ],
  },
  {
    slug: '2026-03-16',
    dateLabel: '2026年3月16日',
    title: '2026年3月16日 殿堂発表',
    description: '2026年3月16日の殿堂発表で指定されたカードを振り返るページです。',
    cards: [
      {
        name: '《ビックリ・イリュージョン》',
        initial: '殿堂入り → プレミアム殿堂',
        description: '',
        history: ['無制限', '殿堂入り', 'プレミアム殿堂'],
        imageUrl: officialImage('dm20-035'),
        officialUrl: officialPage('dm20-035'),
      },
      {
        name: '《【今すぐ】うわっ…相手の攻撃止めすぎ…？【クリック】》',
        initial: '無制限 → プレミアム殿堂',
        description: '',
        history: ['無制限', 'プレミアム殿堂'],
        imageUrl: officialImage('dmex14-046'),
        officialUrl: officialPage('dmex14-046'),
      },
      {
        name: '《愛銀河マーキュリー・スターフォージ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dm25ex1-023'),
        officialUrl: officialPage('dm25ex1-023'),
      },
      {
        name: '《闇王ゼーロ》',
        initial: '無制限 → 殿堂入り',
        description: '',
        history: ['無制限', '殿堂入り'],
        imageUrl: officialImage('dmex15-b016'),
        officialUrl: officialPage('dmex15-b016'),
      },
      {
        name: '《バジュラズ・ソウル》',
        initial: '殿堂入り → 無制限',
        description: '',
        history: ['無制限', '殿堂入り', '無制限'],
        imageUrl: officialImage('dm15-s04'),
        officialUrl: officialPage('dm15-s04'),
      },
    ],
  },
]

/** スラッグから殿堂特集エントリを取得（なければ null） */
export function getHallEntry(slug: string): HallEntry | null {
  return HALL_OF_FAME_ENTRIES.find(e => e.slug === slug) ?? null
}

/** 施行年（4桁）一覧を昇順で返す（例: ['2004','2005','2006','2007']） */
export function getHallYears(): string[] {
  const years = new Set(HALL_OF_FAME_ENTRIES.map(e => e.slug.slice(0, 4)))
  return Array.from(years).sort()
}

/** 指定した施行年のエントリ一覧を日付順（配列定義順）で返す */
export function getEntriesByYear(year: string): HallEntry[] {
  return HALL_OF_FAME_ENTRIES.filter(e => e.slug.startsWith(`${year}-`))
}

/**
 * 1施行日エントリから代表カード画像を最大3枚集める（年ページの日付カード用サムネ）。
 * コンビ殿堂など images を持つカードはその画像を優先し、無ければ各カードの imageUrl を使う。
 */
export function getEntryThumbnails(entry: HallEntry): { src: string; name: string }[] {
  const out: { src: string; name: string }[] = []
  for (const card of entry.cards) {
    if (card.images && card.images.length > 0) {
      for (const img of card.images) {
        out.push({ src: img.src, name: img.name })
        if (out.length >= 3) return out
      }
    } else if (card.imageUrl) {
      out.push({ src: card.imageUrl, name: card.name })
      if (out.length >= 3) return out
    }
  }
  return out
}

/** 指定した施行年の先頭カード画像を最大3枚集める（殿堂図鑑トップの年度カード用サムネ）。 */
export function getYearThumbnails(year: string): { src: string; name: string }[] {
  const out: { src: string; name: string }[] = []
  for (const entry of getEntriesByYear(year)) {
    for (const thumb of getEntryThumbnails(entry)) {
      out.push(thumb)
      if (out.length >= 3) return out
    }
  }
  return out
}
