ALTER TABLE notices
  ADD COLUMN IF NOT EXISTS columns INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS header_text TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS items JSONB NOT NULL DEFAULT '[]';
