'use client'
import { ChangeEvent, useState, useTransition } from 'react'
import type { CardImportResult } from '@/lib/card-import'
import { getCardMissingFields } from '@/lib/card-completeness'

const sample = JSON.stringify([{ name: '飛翔龍 5000VT', image_url: 'https://example.com/card.jpg', civilization: ['水'], cost: 8, card_type: 'クリーチャー', regulation: 'none' }], null, 2)

export default function CardImportClient() {
  const [json, setJson] = useState(sample), [result, setResult] = useState<CardImportResult | null>(null), [message, setMessage] = useState(''), [confirmed, setConfirmed] = useState(false), [pending, startTransition] = useTransition()
  async function call(url: string, body: unknown) { const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? data.message ?? '失敗しました'); return data }
  function validate() { setMessage(''); setConfirmed(false); startTransition(async () => { try { setResult(await call('/api/admin/cards/import/validate', { json })) } catch (e) { setMessage(e instanceof Error ? e.message : '検証失敗') } }) }
  function register() { startTransition(async () => { try { const data = await call('/api/admin/cards/import/register', { json, confirmed }); setMessage(data.message); await setResult(await call('/api/admin/cards/import/validate', { json })) } catch (e) { setMessage(e instanceof Error ? e.message : '登録失敗') } }) }
  async function loadFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) { setJson(await file.text()); setResult(null); setConfirmed(false) } }
  return <div className="mt-5 grid gap-4 lg:grid-cols-2"><section className="rounded border bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">1. JSON入力</h2><label className="cursor-pointer rounded border px-3 py-1.5 text-xs font-bold">JSONファイルを読み込む<input type="file" accept="application/json,.json" onChange={loadFile} className="hidden" /></label></div><textarea value={json} onChange={e => { setJson(e.target.value); setResult(null); setConfirmed(false) }} className="h-[520px] w-full rounded border bg-gray-50 p-3 font-mono text-xs"/><button onClick={validate} disabled={pending} className="mt-3 rounded bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{pending ? '処理中...' : '検証・プレビュー'}</button></section><section className="rounded border bg-white p-4"><h2 className="font-bold">2. 判定結果</h2>{message && <p className="mt-3 rounded border bg-gray-50 p-2 text-sm">{message}</p>}{result && <><div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs">{(['new','update','skip','duplicate'] as const).map(k => <div key={k} className="rounded border p-2"><b className="block text-lg">{result.summary[k]}</b>{k}</div>)}</div>{!result.databaseChecked && <p className="mt-3 rounded border border-yellow-300 bg-yellow-50 p-2 text-xs text-yellow-800">cards migration未適用のためDB重複照合は未実行です。入力プレビューのみ利用できます。</p>}<div className="mt-3 max-h-[420px] overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th>行</th><th>カード</th><th>正規化名</th><th>判定</th></tr></thead><tbody>{result.rows.map(row => { const missing = getCardMissingFields(row); return <tr key={row.row} className="border-b align-top"><td className="py-2">{row.row}</td><td className="py-2"><b>{row.name}</b><div className="text-gray-500">{row.civilization.join('/')} / {row.cost ?? '-'} / {row.card_type ?? '-'}</div>{missing.length > 0 && <div className="font-bold text-amber-700">未完成: {missing.join('・')}</div>}{row.errors.map(e => <div key={e} className="text-red-700">{e}</div>)}</td><td className="py-2 font-mono">{row.normalized_name}</td><td className="py-2 font-bold">{row.status}</td></tr> })}</tbody></table></div><p className="mt-3 text-xs text-gray-500">未完成のまま登録しても、共通カード管理の「未完成カード」へ自動的に表示されます。</p><label className="mt-4 flex gap-2 text-xs"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>内容を確認し、Preview DBへ新規登録・更新する</label><button onClick={register} disabled={!result.ok || !result.databaseChecked || !confirmed || pending} className="mt-3 rounded bg-green-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Preview DBへ登録</button></>}</section></div>
}
