import { writeFile } from 'node:fs/promises'
import { getCurrentHallCards, getHallCardOfficialId } from '../src/lib/hall-of-fame'
import { normalizeCardName } from '../src/lib/card-import'

const cards = getCurrentHallCards()
const rows = cards.map(card => {
  const sourceKey = getHallCardOfficialId(card)
  if (!sourceKey) throw new Error(`公式カードIDなし: ${card.name}`)
  return {
    sourceKey,
    name: card.name.replace(/^《|》$/g, ''),
    normalizedName: normalizeCardName(card.name.replace(/^《|》$/g, '')),
    imageUrl: card.imageUrl ?? null,
    regulation: card.status === 'hall' ? 'hall' : 'premium_hall',
  }
})

if (rows.length !== 128) throw new Error(`同期対象が128枚ではありません: ${rows.length}`)
if (rows.filter(row => row.regulation === 'hall').length !== 89) throw new Error('殿堂が89枚ではありません')
if (rows.filter(row => row.regulation === 'premium_hall').length !== 39) throw new Error('プレ殿が39枚ではありません')
if (new Set(rows.map(row => row.sourceKey)).size !== rows.length) throw new Error('公式カードIDが重複しています')

const q = (value: string | null) => value === null ? 'null' : `'${value.replaceAll("'", "''")}'`
const values = rows.map((row, index) =>
  `  (${index + 1},${q(row.sourceKey)},${q(row.name)},${q(row.normalizedName)},${q(row.imageUrl)},${q(row.regulation)})`,
).join(',\n')

const sql = `-- GENERATED by scripts/generate-hall-release-card-sync.mts
-- 思い出図鑑の現在状態（history末尾）から抽出。maker企画作成migrationより先に適用する。
alter table public.cards add column if not exists source_kind text;
alter table public.cards add column if not exists source_key text;
create unique index if not exists cards_source_identity_unique
  on public.cards(source_kind,source_key) where source_kind is not null and source_key is not null;

create temporary table hall_release_card_sync(
  sort_order integer primary key, source_key text not null unique, name text not null,
  normalized_name text not null unique, image_url text, regulation text not null
) on commit drop;
insert into hall_release_card_sync(sort_order,source_key,name,normalized_name,image_url,regulation) values
${values};

do $$ begin
  if (select count(*) from hall_release_card_sync) <> 128
    or (select count(*) from hall_release_card_sync where regulation='hall') <> 89
    or (select count(*) from hall_release_card_sync where regulation='premium_hall') <> 39 then
    raise exception 'HALL_RELEASE_SYNC_COUNT_MISMATCH';
  end if;
  if exists (
    select 1 from hall_release_card_sync s join public.cards c on c.normalized_name=s.normalized_name
    where (c.source_kind,c.source_key) is distinct from ('takaratomy_card_id',s.source_key)
  ) then raise exception 'HALL_RELEASE_NORMALIZED_NAME_COLLISION'; end if;
end $$;

insert into public.cards(name,normalized_name,image_url,civilization,cost,card_type,regulation,is_active,source_kind,source_key)
select name,normalized_name,image_url,'{}'::text[],null,null,regulation,true,'takaratomy_card_id',source_key
from hall_release_card_sync
on conflict do nothing;

-- 《幻緑の双月／母なる星域》だけ、既存カードも同期元の正しいa面URLへ追従させる。
update public.cards c
set image_url=s.image_url
from hall_release_card_sync s
where c.source_kind='takaratomy_card_id' and c.source_key=s.source_key
  and s.source_key='dmex04-052'
  and c.image_url is distinct from s.image_url;

do $$ begin
  if (select count(*) from hall_release_card_sync s join public.cards c
      on c.source_kind='takaratomy_card_id' and c.source_key=s.source_key and c.is_active) <> 128 then
    raise exception 'HALL_RELEASE_CARDS_NOT_FULLY_LINKED';
  end if;
end $$;
`

await writeFile(new URL('../supabase/migrations/20260713_01_hall_release_card_sync.sql', import.meta.url), sql)
console.log(`generated ${rows.length} cards`)
