import { cookies } from 'next/headers'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ADMIN_COOKIE, verifyAdminCookie } from '@/lib/admin-auth'
import { createAdminClient } from '@/lib/supabase-admin'
import { saveSelectProject } from './actions'

export const dynamic = 'force-dynamic'
export default async function SelectProjectsAdminPage() {
  if (!verifyAdminCookie((await cookies()).get(ADMIN_COOKIE)?.value)) notFound()
  const { data: projects } = await createAdminClient().from('maker_projects').select('slug,title,status,is_public,config').eq('type', 'select').order('created_at')
  return <main className="min-h-screen bg-slate-50 px-3 py-6"><div className="mx-auto max-w-5xl"><Link href="/admin" className="text-sm font-bold text-blue-700">← 管理画面</Link><h1 className="mt-3 text-2xl font-black">SELECT型企画管理</h1><p className="mt-1 text-sm text-gray-600">設定だけで1〜12枚のカード選択企画を追加・更新できます。</p>
    <div className="mt-5 space-y-5">{[...(projects ?? []), { slug:'',title:'',status:'draft',is_public:false,config:{} }].map((project,index) => { const c = project.config as Record<string, unknown>; return <form action={saveSelectProject} key={project.slug || `new-${index}`} className="rounded-xl border bg-white p-4"><h2 className="font-black">{project.slug ? project.title : '新しい企画'}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">
      <label className="text-sm">slug<input name="slug" defaultValue={project.slug} required className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">企画タイトル<input name="title" defaultValue={project.title} required className="mt-1 w-full rounded border p-2"/></label>
      <label className="text-sm sm:col-span-2">説明<textarea name="description" defaultValue={String(c.description ?? '')} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">最小枚数<input name="minChoices" type="number" min="1" max="12" defaultValue={Number(c.minChoices ?? 1)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">最大枚数<input name="maxChoices" type="number" min="1" max="12" defaultValue={Number(c.maxChoices ?? 1)} className="mt-1 w-full rounded border p-2"/></label>
      <label className="text-sm">重複<select name="duplicateRule" defaultValue={String(c.duplicateRule ?? 'card_name')} className="mt-1 w-full rounded border p-2"><option value="card_name">同名禁止</option><option value="card_id">同一ID禁止</option></select></label><label className="text-sm">カードプール<select name="cardPool" defaultValue={String(c.cardPool ?? 'all')} className="mt-1 w-full rounded border p-2"><option value="all">全カード</option><option value="manual">手動リスト</option></select></label>
      <label className="text-sm">画像タイトル<input name="resultTitle" defaultValue={String(c.resultTitle ?? project.title)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">既定投稿タイトル<input name="defaultTitle" defaultValue={String(c.defaultTitle ?? '')} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">既定コメント<input name="defaultComment" defaultValue={String(c.defaultComment ?? '')} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">X共有文<textarea name="shareText" defaultValue={String(c.shareText ?? '')} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">ハッシュタグ<input name="hashtag" defaultValue={String(c.hashtag ?? '')} className="mt-1 w-full rounded border p-2"/></label>
    </div><div className="mt-3 flex flex-wrap gap-3 text-sm">{[['published','公開',project.is_public],['exactChoices','指定枚数必須',c.exactChoices!==false],['reorderable','並び替え',c.reorderable!==false],['showTitle','タイトル入力',c.showTitle!==false],['showComment','コメント入力',c.showComment!==false],['showSubmissions','投稿一覧',c.showSubmissions!==false],['showAggregates','カード集計',c.showAggregates!==false],['showZeroVotes','0票表示',c.showZeroVotes===true],['autoRegisterOnImageSave','保存時登録',c.autoRegisterOnImageSave!==false],['defaultListPublic','一覧掲載初期ON',c.defaultListPublic!==false]].map(([name,label,checked])=><label key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)}/> {String(label)}</label>)}</div><button className="mt-4 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">保存</button></form>})}</div>
  </div></main>
}
