import { cookies } from 'next/headers'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ADMIN_COOKIE, verifyAdminCookie } from '@/lib/admin-auth'
import { createAdminClient } from '@/lib/supabase-admin'
import { MAKER_CATEGORIES, MAKER_CATEGORY_LABELS, parseMakerCatalogConfig } from '@/lib/maker-catalog'
import { saveMakerCatalogSettings, saveSelectProject } from './actions'

export const dynamic = 'force-dynamic'
type Project = { slug: string; title: string; type: string; status: string; is_public: boolean; config: Record<string, unknown> | null }

export default async function MakersAdminPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string }> }) {
  if (!verifyAdminCookie((await cookies()).get(ADMIN_COOKIE)?.value)) notFound()
  const sp = await searchParams
  const { data } = await createAdminClient().from('maker_projects').select('slug,title,type,status,is_public,config').order('created_at')
  const projects = ((data ?? []) as Project[]).filter(p => (!sp.q || `${p.title} ${p.slug}`.toLowerCase().includes(sp.q.toLowerCase())) && (!sp.category || parseMakerCatalogConfig(p).category === sp.category))
  return <main className="min-h-screen bg-slate-50 px-3 py-6"><div className="mx-auto max-w-6xl"><Link href="/admin" className="text-sm font-bold text-blue-700">← 管理画面</Link><h1 className="mt-3 text-2xl font-black">デュエマあそびば企画管理</h1><p className="mt-1 text-sm text-gray-600">公開状態と一覧掲載、カテゴリ、並び順、期間、バッジを共通設定します。</p>
    <form className="mt-4 flex flex-wrap gap-2 rounded-xl border bg-white p-3"><input name="q" defaultValue={sp.q} placeholder="企画名・slugで検索" className="rounded border p-2 text-sm"/><select name="category" defaultValue={sp.category} className="rounded border p-2 text-sm"><option value="">全カテゴリ</option>{MAKER_CATEGORIES.filter(c=>c!=='archive').map(c=><option key={c} value={c}>{MAKER_CATEGORY_LABELS[c]}</option>)}</select><button className="rounded bg-slate-800 px-4 text-sm font-bold text-white">絞り込む</button></form>
    <div className="mt-5 space-y-4">{projects.map(project => { const c = parseMakerCatalogConfig(project); return <form action={saveMakerCatalogSettings} key={project.slug} className="rounded-xl border bg-white p-4"><input type="hidden" name="slug" value={project.slug}/><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-black">{project.title}</h2><p className="text-xs text-gray-500">{project.slug} ・ {project.status}/{project.is_public ? '公開' : '非公開'}</p></div><button className="rounded bg-blue-700 px-4 py-2 text-sm font-bold text-white">一覧設定を保存</button></div><div className="mt-3 grid gap-3 sm:grid-cols-4">
      <label className="text-sm">カテゴリ<select name="category" defaultValue={c.category} className="mt-1 w-full rounded border p-2">{MAKER_CATEGORIES.filter(x=>x!=='archive').map(x=><option key={x} value={x}>{MAKER_CATEGORY_LABELS[x]}</option>)}</select></label><label className="text-sm">表示順<input name="sortOrder" type="number" defaultValue={c.sortOrder} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">開始日時<input name="startsAt" type="datetime-local" defaultValue={c.startsAt.slice(0,16)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">終了日時<input name="endsAt" type="datetime-local" defaultValue={c.endsAt.slice(0,16)} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">短い説明<input name="shortDescription" defaultValue={c.shortDescription} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">サムネイルURL<input name="thumbnailUrl" type="url" defaultValue={c.thumbnailUrl} className="mt-1 w-full rounded border p-2"/></label>
    </div><div className="mt-3 flex flex-wrap gap-4 text-sm">{([['showInCatalog','一覧掲載',c.showInCatalog],['featured','おすすめ',c.featured],['isNew','NEW',c.isNew],['isLimited','期間限定',c.isLimited],['showInArchive','終了後も過去企画へ掲載',c.showInArchive],['adminOnly','管理者のみ',c.adminOnly]] as const).map(([name,label,checked])=><label key={name}><input type="checkbox" name={name} defaultChecked={checked}/> {label}</label>)}</div></form>})}</div>
    <details className="mt-6 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-black">カード選択企画を新規作成</summary><form action={saveSelectProject} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">slug<input name="slug" required className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">企画タイトル<input name="title" required className="mt-1 w-full rounded border p-2"/></label><label className="text-sm sm:col-span-2">説明<textarea name="description" className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">最小枚数<input name="minChoices" type="number" min="1" max="12" defaultValue="1" className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">最大枚数<input name="maxChoices" type="number" min="1" max="12" defaultValue="1" className="mt-1 w-full rounded border p-2"/></label><input type="hidden" name="duplicateRule" value="card_name"/><input type="hidden" name="cardPool" value="all"/><div className="sm:col-span-2"><label><input type="checkbox" name="published"/> 公開</label><button className="ml-4 rounded bg-blue-700 px-4 py-2 font-bold text-white">作成</button></div></form></details>
  </div></main>
}
