import Link from 'next/link'
import { AnalyticsRefresh } from '@/components/admin/AnalyticsRefresh'
import { getGa4DashboardData, getInternalDashboardData } from '@/lib/admin-dashboard'
import { createAdminClient } from '@/lib/supabase-admin'
import { fetchProjectSummaries, normalizePeriod, type ProjectSummary } from '@/lib/admin-maker-analytics'

function Tabs({ active }: { active: 'site' | 'makers' }) { return <nav className="mb-4 flex gap-2 border-b"><Link prefetch={false} className={`px-4 py-2 text-sm font-bold ${active==='site'?'border-b-2 border-blue-600 text-blue-700':'text-gray-500'}`} href="/admin/analytics?tab=site">サイト全体</Link><Link prefetch={false} className={`px-4 py-2 text-sm font-bold ${active==='makers'?'border-b-2 border-blue-600 text-blue-700':'text-gray-500'}`} href="/admin/analytics?tab=makers">企画一覧</Link></nav> }
function Metric({ label, value, note }: { label:string; value:number|string; note?:string }) { return <div className="rounded-lg border bg-white p-3"><p className="text-xs font-bold text-gray-500">{label}</p><p className="mt-1 text-2xl font-black tabular-nums">{typeof value==='number'?value.toLocaleString('ja-JP'):value}</p>{note&&<p className="mt-1 text-[10px] text-gray-400">{note}</p>}</div> }
function Periods({ period }: { period: string }) { return <div className="flex flex-wrap gap-1">{[['today','今日'],['7d','過去7日'],['30d','過去30日'],['all','全期間']].map(([key,label])=><Link prefetch={false} key={key} href={`/admin/analytics?tab=makers&period=${key}`} className={`rounded border px-3 py-1.5 text-xs font-bold ${period===key?'border-blue-500 bg-blue-50 text-blue-700':'bg-white text-gray-600'}`}>{label}</Link>)}</div> }

export default async function Page({ searchParams }: { searchParams: Promise<{ tab?: string; period?: string }> }) {
  const sp=await searchParams; const active=sp.tab==='makers'?'makers':'site'; const updatedAt=new Date().toISOString()
  if(active==='site') {
    const [ga4,internal]=await Promise.all([getGa4DashboardData(28),getInternalDashboardData(createAdminClient())])
    return <><Tabs active="site"/><div className="mb-3"><AnalyticsRefresh updatedAt={updatedAt}/></div>{ga4.ok?<><section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Metric label="今日PV" value={ga4.summary.todayViews}/><Metric label="過去7日PV" value={ga4.summary.sevenDayViews}/><Metric label="過去28日PV" value={ga4.summary.twentyEightDayViews}/><Metric label="今日のユーザー数" value={ga4.summary.todayUsers}/><Metric label="過去7日のユーザー数" value={ga4.summary.sevenDayUsers}/><Metric label="1ユーザーあたりPV（28日）" value={ga4.trendSummary.viewsPerUser.toFixed(2)}/></section><p className="mt-2 text-[11px] text-gray-500">既存GA4 Data APIと同じ集計式・JST境界・5分キャッシュを使用しています。</p></>:<div className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">GA4の取得に失敗しました: {ga4.error}</div>}
      <section className="mt-5"><h2 className="mb-2 font-black">掲示板内部の累計指標</h2><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric label="スレ総閲覧数" value={internal.totals.totalViews}/><Metric label="スレ数" value={internal.totals.threadCount}/><Metric label="コメント数" value={internal.totals.commentCount}/><Metric label="平均閲覧数" value={internal.totals.avgViews}/></div></section>
      <section className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded border bg-white p-4"><h2 className="font-black">人気ページ（直近7日）</h2>{ga4.ok?<ol className="mt-2 divide-y">{ga4.topPages.map(row=><li key={row.path} className="flex justify-between gap-3 py-2 text-sm"><span className="min-w-0 truncate">{row.path}</span><span className="shrink-0 font-bold tabular-nums">{row.views.toLocaleString()} PV</span></li>)}</ol>:<p className="mt-2 text-sm text-gray-500">GA4取得失敗のため表示できません。</p>}</div><div className="rounded border bg-white p-4"><h2 className="font-black">最近コメントが増えたスレ</h2>{internal.recentCommentThreads.length?<ol className="mt-2 divide-y">{internal.recentCommentThreads.map(row=><li key={row.id} className="flex justify-between gap-3 py-2 text-sm"><Link href={`/thread/${row.id}`} className="min-w-0 truncate text-blue-700 hover:underline">{row.title}</Link><span className="shrink-0 font-bold tabular-nums">+{row.recentComments}</span></li>)}</ol>:<p className="mt-2 text-sm text-gray-500">直近24時間のコメント増加は0件です。</p>}</div></section></>
  }
  const period=normalizePeriod(sp.period); let projects: ProjectSummary[] = []; let error=''; try { projects=await fetchProjectSummaries(period) } catch(e){ error=e instanceof Error?e.message:'企画一覧を取得できませんでした' }
  return <><Tabs active="makers"/><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><Periods period={period}/><AnalyticsRefresh updatedAt={updatedAt}/></div>{error?<div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error} ページを再読み込みして再試行してください。</div>:projects.length===0?<div className="rounded border bg-white p-6 text-center text-sm text-gray-500">表示できる企画は0件です。</div>:<><div className="hidden overflow-hidden rounded border bg-white md:block"><table className="w-full text-xs"><thead className="bg-gray-100 text-left"><tr>{['企画','公開','PV / 利用者','回答','操作','共有・閲覧','登録'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{projects.map(p=><tr key={p.id} className="border-t align-top"><td className="p-3"><Link prefetch={false} href={`/admin/analytics/makers/${p.slug}?period=${period}`} className="font-bold text-blue-700 hover:underline">{p.title}</Link><div className="text-[10px] text-gray-400">{p.slug}</div></td><td className="p-3">{p.isPublic&&p.status==='published'?'公開':'非公開'}</td><td className="p-3">今日 {p.todayPv} PV<br/>期間 {p.pv} PV<br/>{p.uniqueActors} 利用者</td><td className="p-3">{p.registrants} 人<br/>{p.submissions} 件</td><td className="p-3">開始 {p.events.tier_created}<br/>保存 {p.events.image_saved}</td><td className="p-3">X {p.events.x_shared}<br/>集計 {p.events.aggregate_viewed}</td><td className="p-3">{p.events.signup_completed}</td></tr>)}</tbody></table></div><div className="space-y-2 md:hidden">{projects.map(p=><Link prefetch={false} key={p.id} href={`/admin/analytics/makers/${p.slug}?period=${period}`} className="block rounded-lg border bg-white p-3"><div className="flex justify-between gap-2"><p className="font-bold text-blue-700">{p.title}</p><span className="text-xs">{p.isPublic?'公開':'非公開'}</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><span>今日PV <b>{p.todayPv}</b></span><span>期間PV <b>{p.pv}</b></span><span>利用者 <b>{p.uniqueActors}</b></span><span>回答 <b>{p.submissions}</b></span><span>保存 <b>{p.events.image_saved}</b></span><span>X共有 <b>{p.events.x_shared}</b></span></div></Link>)}</div></>}</>
}
