import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AnalyticsRefresh } from '@/components/admin/AnalyticsRefresh'
import { fetchProjectDetail, normalizePeriod } from '@/lib/admin-maker-analytics'

const labels:Record<string,string>={s:'S',a:'A',b:'B',c:'C',d:'D',release:'選択'}
function rate(a:number,b:number){return b?`${(a/b*100).toFixed(1)}%`:'—'}
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{period?:string}>}){
 const {slug}=await params; const sp=await searchParams; const period=normalizePeriod(sp.period); const detail=await fetchProjectDetail(slug,period); if(!detail)notFound()
 const interaction=detail.events.tier_created; const submit=detail.submissions; const share=detail.events.image_saved+detail.events.x_shared
 return <><div className="mb-3"><Link href={`/admin/analytics?tab=makers&period=${period}`} className="text-xs text-blue-700 hover:underline">← 企画一覧</Link><h2 className="mt-2 text-xl font-black">{detail.title}</h2><p className="text-xs text-gray-500">{detail.slug} / {detail.type}</p></div><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1">{[['today','今日'],['7d','過去7日'],['30d','過去30日'],['all','全期間']].map(([k,l])=><Link key={k} href={`?period=${k}`} className={`rounded border px-3 py-1.5 text-xs font-bold ${period===k?'border-blue-500 bg-blue-50 text-blue-700':'bg-white'}`}>{l}</Link>)}</div><AnalyticsRefresh updatedAt={new Date().toISOString()}/></div>
 <section className="grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{[['PV',detail.pv],['ユニーク利用者',detail.uniqueActors],['企画を操作',interaction],['回答登録者',detail.registrants],['回答件数',submit],['画像保存',detail.events.image_saved],['X共有',detail.events.x_shared],['集計閲覧',detail.events.aggregate_viewed],['新規登録',detail.events.signup_completed]].map(([l,v])=><div key={String(l)} className="rounded border bg-white p-3"><p className="text-xs font-bold text-gray-500">{l}</p><p className="text-2xl font-black tabular-nums">{Number(v).toLocaleString()}</p></div>)}</section>
 <section className="mt-5 rounded border bg-white p-4"><h3 className="font-black">段階間の参考割合</h3><p className="mt-1 text-xs text-gray-500">イベント件数・回答件数を前段階の件数で割った概算です。同一ユーザーの遷移は保証しません。</p><div className="mt-3 grid gap-2 sm:grid-cols-4">{[[`ページ閲覧`,detail.pv,'—'],['企画を操作',interaction,rate(interaction,detail.pv)],['回答を登録',submit,rate(submit,interaction)],['画像保存・X共有',share,rate(share,submit)]].map(([l,v,r])=><div key={String(l)} className="rounded bg-gray-50 p-3"><p className="text-xs font-bold">{l}</p><p className="text-xl font-black">{v}</p><p className="text-xs text-gray-500">前段階比 {r}</p></div>)}</div></section>
 <section className="mt-5"><h3 className="font-black">回答内容・人気カード</h3><p className="mb-2 text-xs text-gray-500">企画カードを基準に0票も表示。{detail.type==='tier'?'平均Tierとグループ分布':'選択人数と選択率'}を表示します。</p><div className="overflow-hidden rounded border bg-white"><div className="divide-y">{detail.answers.map(a=><div key={a.cardId} className="grid grid-cols-[1fr_auto] gap-3 p-3 text-sm"><div><p className="font-bold">{a.name}</p><p className="text-xs text-gray-500">{Object.entries(a.groups).map(([k,v])=>`${labels[k]??k}: ${v}`).join(' / ')}</p></div><div className="text-right"><p className="font-black">{a.total}{detail.type==='tier'?'票':'人'}</p><p className="text-xs text-gray-500">{detail.type==='tier'?`平均 ${a.average??'—'}`:`選択率 ${a.rate}%`}</p></div></div>)}</div></div></section></>
}
