'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import { DECK_STORAGE_KEY,DECK_STORAGE_VERSION,MAX_DECK_CARDS,MAX_SAME_CARD,deckSize,type DeckCard,type DeckEntry } from '@/lib/deck-maker'
const proxy=(url:string)=>`/api/card-image?url=${encodeURIComponent(url)}`
function Art({card}:{card:DeckCard}){const[failed,setFailed]=useState(false);return !card.imageUrl||failed?<div data-testid="card-placeholder" className="flex aspect-[5/7] items-center justify-center bg-slate-800 p-2 text-center text-xs font-bold text-white">{card.name}</div>:<img src={proxy(card.imageUrl)} alt={card.name} className="aspect-[5/7] object-cover" onError={()=>setFailed(true)}/>}
async function load(card:DeckCard){if(!card.imageUrl)return null;return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=proxy(card.imageUrl!)})}
export default function DeckMaker(){const[query,setQuery]=useState(''),[results,setResults]=useState<DeckCard[]>([]),[entries,setEntries]=useState<DeckEntry[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState('');const requestId=useRef(0),total=deckSize(entries)
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(DECK_STORAGE_KEY)??'null') as {version?:number;entries?:DeckEntry[]}|null;if(saved?.version===DECK_STORAGE_VERSION&&Array.isArray(saved.entries)){const restored=saved.entries.filter(x=>x&&typeof x.id==='string'&&Number.isInteger(x.count)&&x.count>0).slice(0,40);setEntries(restored);const ids=restored.map(x=>x.id);if(ids.length)fetch('/api/cards/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})}).then(r=>r.json()).then(({cards}:{cards:DeckCard[]})=>{const latest=new Map(cards.map(c=>[c.id,c]));setEntries(current=>current.map(e=>({...e,...(latest.get(e.id)??{})})))})}}catch{localStorage.removeItem(DECK_STORAGE_KEY)}setReady(true)},[])
useEffect(()=>{if(ready)localStorage.setItem(DECK_STORAGE_KEY,JSON.stringify({version:DECK_STORAGE_VERSION,entries}))},[entries,ready])
useEffect(()=>{if(!query.trim()){setResults([]);return}const id=++requestId.current,timer=window.setTimeout(()=>fetch(`/api/cards/search?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(data=>{if(id===requestId.current)setResults(data.cards??[])}).catch(()=>setResults([])),300);return()=>clearTimeout(timer)},[query])
const byId=useMemo(()=>new Map(entries.map(e=>[e.id,e])),[entries]);function add(card:DeckCard){const current=byId.get(card.id);if(total>=MAX_DECK_CARDS)return setNotice('メインデッキは40枚までです');if(current&&current.count>=MAX_SAME_CARD)return setNotice('同名カードは4枚までです');setEntries(list=>current?list.map(e=>e.id===card.id?{...e,count:e.count+1}:e):[...list,{...card,count:1}]);setNotice('')}function remove(id:string){setEntries(list=>list.flatMap(e=>e.id!==id?[e]:e.count>1?[{...e,count:e.count-1}]:[]))}
async function savePng(){const cards=entries.flatMap(e=>Array.from({length:e.count},()=>e));if(!cards.length)return setNotice('カードを追加してください');const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),w=130,h=182,g=10,cols=8,p=44;canvas.width=1200;canvas.height=220+Math.ceil(cards.length/cols)*(h+g);if(!ctx)return;ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#0f172a';ctx.font='bold 44px sans-serif';ctx.fillText('デュエマ デッキ',p,64);ctx.font='24px sans-serif';ctx.fillText(`${cards.length}/40枚`,p,104);const images=await Promise.all(cards.map(load));cards.forEach((card,i)=>{const x=p+i%cols*(w+g),y=130+Math.floor(i/cols)*(h+g);if(images[i])ctx.drawImage(images[i]!,x,y,w,h);else{ctx.fillStyle='#1e293b';ctx.fillRect(x,y,w,h);ctx.fillStyle='#fff';ctx.font='bold 14px sans-serif';ctx.fillText(card.name.slice(0,12),x+6,y+h/2)}});ctx.fillStyle='#475569';ctx.font='16px sans-serif';ctx.fillText('非公式ファンサービス / © TOMY',p,canvas.height-24);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='duema-deck.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
return <div className="grid gap-5 lg:grid-cols-[420px_1fr]"><section className="rounded-2xl bg-white p-4 shadow"><label htmlFor="card-search" className="font-black">カード検索</label><input id="card-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="カード名・読み仮名" className="mt-2 w-full rounded-xl border px-4 py-3"/><p className="mt-2 text-xs text-slate-500">0.3秒後に検索・最大30件</p><div data-testid="search-results" className="mt-3 grid grid-cols-2 gap-3">{results.map(card=><article key={card.id} className="overflow-hidden rounded-xl border"><Art card={card}/><div className="p-2"><p className="line-clamp-2 min-h-10 text-sm font-bold">{card.name}</p><button onClick={()=>add(card)} className="mt-2 w-full rounded-lg bg-emerald-700 py-2 font-bold text-white">追加</button>{card.officialPageUrl&&<a href={card.officialPageUrl} target="_blank" rel="noreferrer" className="mt-2 block text-center text-xs text-blue-700 underline">公式ページ</a>}</div></article>)}</div></section><section className="rounded-2xl bg-white p-4 shadow"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">メインデッキ</h2><p data-testid="deck-count" className="text-2xl font-black text-emerald-800">{total} / 40枚</p></div><div className="flex gap-2"><button onClick={savePng} className="rounded-xl bg-blue-700 px-3 py-2 font-bold text-white">PNG保存</button><button onClick={()=>{setEntries([]);setNotice('リセットしました')}} className="rounded-xl border border-red-300 px-3 py-2 font-bold text-red-700">リセット</button></div></div>{notice&&<p role="status" className="mt-3 rounded bg-amber-50 p-2 font-bold">{notice}</p>}<div data-testid="deck-list" className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-5">{entries.map(e=><article key={e.id} className="relative overflow-hidden rounded-xl border"><Art card={e}/><span className="absolute right-1 top-1 rounded-full bg-black/80 px-2 py-1 font-black text-white">×{e.count}</span><div className="p-2"><p className="line-clamp-2 text-xs font-bold">{e.name}</p><div className="mt-2 grid grid-cols-2 gap-1"><button onClick={()=>remove(e.id)} aria-label={`${e.name}を1枚減らす`} className="rounded bg-slate-200">−</button><button onClick={()=>add(e)} aria-label={`${e.name}を1枚増やす`} className="rounded bg-emerald-700 text-white">＋</button></div></div></article>)}</div><p className="mt-6 border-t pt-4 text-xs text-slate-500">当サービスは権利者各社とは関係のない非公式ファンサービスです。カード画像・名称等の権利は各権利者に帰属します。© TOMY</p></section></div>}
