-- GENERATED by scripts/generate-hall-release-card-sync.mts
-- 思い出図鑑の現在状態（history末尾）から抽出。maker企画作成migrationより先に適用する。
alter table public.cards add column if not exists source_kind text;
alter table public.cards add column if not exists source_key text;
create unique index if not exists cards_source_identity_unique
  on public.cards(source_kind,source_key) where source_kind is not null and source_key is not null;

create temporary table hall_release_card_sync(
  sort_order integer primary key, source_key text not null unique, name text not null,
  normalized_name text not null unique, image_url text, regulation text not null
) on commit drop;
insert into hall_release_card_sync(sort_order,source_key,name,normalized_name,image_url,regulation) values
  (1,'dmrp06-m01','“轟轟轟”ブランド','“轟轟轟”ブランド','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp06-m01.jpg','hall'),
  (2,'dmrp04m-016','“龍装”チュリス','“龍装”チュリス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp04m-016.jpg','hall'),
  (3,'dm22ex1-008','「無月」の頂 ＄スザーク＄','「無月」の頂$スザーク$','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm22ex1-008.jpg','hall'),
  (4,'dmex14-046','【今すぐ】うわっ…相手の攻撃止めすぎ…？【クリック】','【今すぐ】うわっ...相手の攻撃止めすぎ...?【クリック】','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex14-046.jpg','premium_hall'),
  (5,'dmrp09-s09','BAKUOOON・ミッツァイル','BAKUOOON・ミッツァイル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp09-s09.jpg','hall'),
  (6,'dm23rp4-S02','DARK MATERIAL COMPLEX','DARKMATERIALCOMPLEX','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm23rp4-S02.jpg','hall'),
  (7,'dm23rp1-S3','der''Zen Mondo／♪必殺で つわものどもが 夢の跡','der''ZenMondo/♪必殺でつわものどもが夢の跡','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm23rp1-S3a.jpg','premium_hall'),
  (8,'dmr23-030','Dの牢閣 メメント守神宮','Dの牢閣メメント守神宮','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr23-030.jpg','hall'),
  (9,'dmrp10-010','MEGATOON・ドッカンデイヤー','MEGATOON・ドッカンデイヤー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp10-010.jpg','hall'),
  (10,'dmr19-s09','S級原始 サンマッド','S級原始サンマッド','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr19-s09.jpg','hall'),
  (11,'dm15-002','アクア・パトロール','アクア・パトロール','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm15-002.jpg','premium_hall'),
  (12,'dm37-010','アクア・メルゲ','アクア・メルゲ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm37-010.jpg','premium_hall'),
  (13,'dm37-051','アラゴト・ムスビ','アラゴト・ムスビ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm37-051.jpg','hall'),
  (14,'dm24ex1-033','アリスの突撃インタビュー','アリスの突撃インタビュー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm24ex1-033.jpg','hall'),
  (15,'dm22-015','インフィニティ・ドラゴン','インフィニティ・ドラゴン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm22-015.jpg','hall'),
  (16,'dm19-027','インフェルノ・ゲート','インフェルノ・ゲート','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm19-027.jpg','premium_hall'),
  (17,'dmc44-001','インフェルノ・サイン','インフェルノ・サイン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmc44-001.jpg','hall'),
  (18,'dmr02-v01','ヴォルグ・サンダー》/《雷獣ヴォルグ・ティーガー','ヴォルグ・サンダー》/《雷獣ヴォルグ・ティーガー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr02-v01a.jpg','premium_hall'),
  (19,'dm03-042','エメラル','エメラル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm03-042.jpg','hall'),
  (20,'dm32-s03','エンペラー・キリコ','エンペラー・キリコ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm32-s03.jpg','hall'),
  (21,'dm27-030','カラフル・ダンス','カラフル・ダンス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm27-030.jpg','hall'),
  (22,'dmex16-061','ガル・ラガンザーク','ガル・ラガンザーク','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex16-061.jpg','hall'),
  (23,'dm12-026','クローン・バイス','クローン・バイス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm12-026.jpg','hall'),
  (24,'dmr17-017','サイバー・I・チョイス','サイバー・I・チョイス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr17-017.jpg','hall'),
  (25,'dmrp05-m02','ジョット・ガン・ジョラゴン','ジョット・ガン・ジョラゴン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp05-m02.jpg','hall'),
  (26,'dm08-014','スケルトン・バイス','スケルトン・バイス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm08-014.jpg','premium_hall'),
  (27,'dm03-011','ストリーミング・シェイパー','ストリーミング・シェイパー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm03-011.jpg','hall'),
  (28,'dm10-048','セイレーン・コンチェルト','セイレーン・コンチェルト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-048.jpg','hall'),
  (29,'dm28-027','ソウル・アドバンテージ','ソウル・アドバンテージ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm28-027.jpg','premium_hall'),
  (30,'dm17-055','ダンディ・ナスオ','ダンディ・ナスオ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm17-055.jpg','premium_hall'),
  (31,'dmrp09-029','ツタンメカーネン','ツタンメカーネン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp09-029.jpg','premium_hall'),
  (32,'dm03-014','デビル・ドレーン','デビル・ドレーン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm03-014.jpg','hall'),
  (33,'dm16-051','ドリル・スコール','ドリル・スコール','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm16-051.jpg','hall'),
  (34,'dm04-011','ハイドロ・ハリケーン','ハイドロ・ハリケーン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm04-011.jpg','hall'),
  (35,'dm27-004','バロン・ゴーヤマ','バロン・ゴーヤマ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm27-004.jpg','hall'),
  (36,'dm20-035','ビックリ・イリュージョン','ビックリ・イリュージョン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm20-035.jpg','premium_hall'),
  (37,'dmr05-022','ヒラメキ・プログラム','ヒラメキ・プログラム','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr05-022.jpg','premium_hall'),
  (38,'dm14-069','フェアリー・ギフト','フェアリー・ギフト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm14-069.jpg','hall'),
  (39,'dm31-025','フォース・アゲイン','フォース・アゲイン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm31-025.jpg','premium_hall'),
  (40,'promoy3-023','フューチャー・スラッシュ','フューチャー・スラッシュ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/promoy3-023.jpg','premium_hall'),
  (41,'dmr23-005','ベイB ジャック','ベイBジャック','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr23-005.jpg','premium_hall'),
  (42,'dmr21-062','ヘブンズ・フォース','ヘブンズ・フォース','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr21-062.jpg','premium_hall'),
  (43,'dm06-057','ヘル・スラッシュ','ヘル・スラッシュ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm06-057.jpg','premium_hall'),
  (44,'dm39-026','ホーガン・ブラスター','ホーガン・ブラスター','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm39-026.jpg','hall'),
  (45,'dm32-015','ポジトロン・サイン','ポジトロン・サイン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm32-015.jpg','hall'),
  (46,'dm16-009','マーシャル・クイーン','マーシャル・クイーン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm16-009.jpg','hall'),
  (47,'dmrp11-028','マリゴルドIII','マリゴルドIII','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp11-028.jpg','premium_hall'),
  (48,'dm26-049','ミラクルとミステリーの扉','ミラクルとミステリーの扉','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm26-049.jpg','hall'),
  (49,'dmr17-s08','メガ・マナロック・ドラゴン','メガ・マナロック・ドラゴン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr17-s08.jpg','hall'),
  (50,'dmrp12-022','ヨミジ 丁-二式','ヨミジ丁-二式','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp12-022.jpg','premium_hall'),
  (51,'dm12-007','ラッキー・ダーツ','ラッキー・ダーツ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm12-007.jpg','hall'),
  (52,'dmx22b-136','レアリティ・レジスタンス','レアリティ・レジスタンス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx22b-136.jpg','premium_hall'),
  (53,'dm09-014','ロスト・チャージャー','ロスト・チャージャー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm09-014.jpg','premium_hall'),
  (54,'dm25ex1-023','愛銀河マーキュリー・スターフォージ','愛銀河マーキュリー・スターフォージ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm25ex1-023.jpg','hall'),
  (55,'dmr18-035','暗黒鎧 ザロスト','暗黒鎧ザロスト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr18-035.jpg','hall'),
  (56,'dmr21-003','暗黒鎧 ダースシスK','暗黒鎧ダースシスK','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr21-003.jpg','hall'),
  (57,'dmex15-b016','闇王ゼーロ','闇王ゼーロ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex15-b016.jpg','hall'),
  (58,'dmrp03-036','一なる部隊 イワシン','一なる部隊イワシン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp03-036.jpg','hall'),
  (59,'dm39-034','陰陽の舞','陰陽の舞','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm39-034.jpg','hall'),
  (60,'dm14-055','怨念怪人ギャスカ','怨念怪人ギャスカ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm14-055.jpg','hall'),
  (61,'dmx23-014','音精 ラフルル','音精ラフルル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx23-014.jpg','premium_hall'),
  (62,'dm30-026','海底鬼面城','海底鬼面城','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm30-026.jpg','hall'),
  (63,'dmr03-019','鎧亜戦隊ディス・マジシャン','鎧亜戦隊ディス・マジシャン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr03-019.jpg','premium_hall'),
  (64,'dm29-s01','奇跡の精霊ミルザム','奇跡の精霊ミルザム','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm29-s01.jpg','premium_hall'),
  (65,'dmex12-022','希望のジョー星','希望のジョー星','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex12-022.jpg','premium_hall'),
  (66,'dmrp05-003','機術士ディール／「本日のラッキーナンバー！」','機術士ディール/「本日のラッキーナンバー!」','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp05-003a.jpg','premium_hall'),
  (67,'dm24rp3-019','逆転の影ガレック','逆転の影ガレック','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm24rp3-019.jpg','hall'),
  (68,'dmr22-l01','禁断機関 VV-8','禁断機関VV-8','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr22-l01.jpg','hall'),
  (69,'dmex08-169','緊急プレミアム殿堂','緊急プレミアム殿堂','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex08-169.jpg','premium_hall'),
  (70,'dm10-015','緊急再誕','緊急再誕','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-015.jpg','hall'),
  (71,'dmex17-054','月下旋壊 ド・リュミーズ','月下旋壊ド・リュミーズ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex17-054.jpg','hall'),
  (72,'dmex04-052','幻緑の双月／母なる星域','幻緑の双月/母なる星域','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex04-052.jpg','hall'),
  (73,'dm29-037','光牙忍ハヤブサマル','光牙忍ハヤブサマル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm29-037.jpg','hall'),
  (74,'dm10-s04','黒神龍ブライゼナーガ','黒神龍ブライゼナーガ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-s04.jpg','hall'),
  (75,'dm10-025','困惑の影トラブル・アルケミスト','困惑の影トラブル・アルケミスト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-025.jpg','hall'),
  (76,'dm36-069','再誕の社','再誕の社','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm36-069.jpg','hall'),
  (77,'dm29-002','斬隠オロチ','斬隠オロチ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm29-002.jpg','hall'),
  (78,'dm24rp2-S05','死神覇王 ブラックXENARCH','死神覇王ブラックXENARCH','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm24rp2-S05.jpg','hall'),
  (79,'dmr22-l03','時の法皇 ミラダンテXII','時の法皇ミラダンテXII','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr22-l03.jpg','hall'),
  (80,'dm11-055','次元の霊峰','次元の霊峰','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm11-055.jpg','hall'),
  (81,'dmr08s-005','疾封怒闘 キューブリック','疾封怒闘キューブリック','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr08s-005.jpg','hall'),
  (82,'dm36-039','蛇手の親分ゴエモンキー！','蛇手の親分ゴエモンキー!','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm36-039.jpg','hall'),
  (83,'dmc58-003','邪神M・ロマノフ','邪神M・ロマノフ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmc58-003.jpg','hall'),
  (84,'dmx18-016','邪帝斧 ボアロアックス》/《邪帝遺跡 ボアロパゴス》/《我臥牙 ヴェロキボアロス','邪帝斧ボアロアックス》/《邪帝遺跡ボアロパゴス》/《我臥牙ヴェロキボアロス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx18-016a.jpg','hall'),
  (85,'dm23ex1-004','邪幽 ジャガイスト','邪幽ジャガイスト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm23ex1-004.jpg','hall'),
  (86,'dm07-019','呪紋の化身','呪紋の化身','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm07-019.jpg','premium_hall'),
  (87,'dmex14-019','樹食の超人','樹食の超人','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex14-019.jpg','hall'),
  (88,'dmrp11-007','瞬閃と疾駆と双撃の決断','瞬閃と疾駆と双撃の決断','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp11-007.jpg','hall'),
  (89,'dmr07-022','瞬封の使徒サグラダ・ファミリア','瞬封の使徒サグラダ・ファミリア','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr07-022.jpg','hall'),
  (90,'dmr02-s05','常勝ディス・オプティマス','常勝ディス・オプティマス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr02-s05.jpg','hall'),
  (91,'dmrp03-020','蝕王の晩餐','蝕王の晩餐','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp03-020.jpg','hall'),
  (92,'dmr20-008','侵革目 パラスラプト','侵革目パラスラプト','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr20-008.jpg','hall'),
  (93,'dmex15-b014','神の試練','神の試練','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex15-b014.jpg','premium_hall'),
  (94,'dmr10-013','凄惨なる牙 パラノーマル','凄惨なる牙パラノーマル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr10-013.jpg','hall'),
  (95,'dmrp11-s12','生命と大地と轟破の決断','生命と大地と轟破の決断','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp11-s12.jpg','premium_hall'),
  (96,'dm26-s03','聖鎧亜キング・アルカディアス','聖鎧亜キング・アルカディアス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm26-s03.jpg','premium_hall'),
  (97,'dm22ex2-021','絶望神サガ','絶望神サガ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm22ex2-021.jpg','hall'),
  (98,'dmr21-l02','蒼き団長 ドギラゴン剣','蒼き団長ドギラゴン剣','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr21-l02.jpg','hall'),
  (99,'dm31-010','蒼狼の始祖アマテラス','蒼狼の始祖アマテラス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm31-010.jpg','premium_hall'),
  (100,'dm10-032','大勇者「鎖風車」','大勇者「鎖風車」','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-032.jpg','hall'),
  (101,'dmd27-003','単騎連射 マグナム','単騎連射マグナム','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmd27-003.jpg','hall'),
  (102,'dmex17-105','超七極 Gio／巨大設計図','超七極Gio/巨大設計図','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex17-105a.jpg','hall'),
  (103,'dmex17-013','超神羅星アポロヌス・ドラゲリオン','超神羅星アポロヌス・ドラゲリオン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmex17-013.jpg','hall'),
  (104,'dm08-s04','超竜バジュラ','超竜バジュラ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm08-s04.jpg','hall'),
  (105,'dm24ex2-017','頂上混成 BAKUONSOOO8th','頂上混成BAKUONSOOO8th','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm24ex2-017.jpg','hall'),
  (106,'dmrp12-s01','天命龍装 ホーリーエンド／ナウ・オア・ネバー','天命龍装ホーリーエンド/ナウ・オア・ネバー','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp12-s01a.jpg','hall'),
  (107,'dm36-015','天雷王機ジョバンニX世','天雷王機ジョバンニX世','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm36-015.jpg','premium_hall'),
  (108,'dm10-021','転生プログラム','転生プログラム','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-021.jpg','premium_hall'),
  (109,'dm16-027','盗掘人形モールス','盗掘人形モールス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm16-027.jpg','hall'),
  (110,'dmd27-014','熱き侵略 レッドゾーンZ','熱き侵略レッドゾーンZ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmd27-014.jpg','hall'),
  (111,'dmx18-001','爆熱剣 バトライ刃》/《爆熱天守 バトライ閣》/《爆熱DX バトライ武神','爆熱剣バトライ刃》/《爆熱天守バトライ閣》/《爆熱DXバトライ武神','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx18-001a.jpg','hall'),
  (112,'dmrp13-018','不敵怪人アンダケイン','不敵怪人アンダケイン','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp13-018.jpg','hall'),
  (113,'dmx09-030','腐敗勇騎ドルマークス','腐敗勇騎ドルマークス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx09-030.jpg','hall'),
  (114,'dmr17-005','復讐 ブラックサイコ','復讐ブラックサイコ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr17-005.jpg','hall'),
  (115,'dm10-036','母なる大地','母なる大地','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-036.jpg','premium_hall'),
  (116,'dm24-030','母なる紋章','母なる紋章','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm24-030.jpg','premium_hall'),
  (117,'dmr14-051','暴龍警報','暴龍警報','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr14-051.jpg','hall'),
  (118,'dm10-026','魔天降臨','魔天降臨','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-026.jpg','hall'),
  (119,'dmrp11-s04','魔導管理室 カリヤドネ／ハーミット・サークル','魔導管理室カリヤドネ/ハーミット・サークル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmrp11-s04a.jpg','hall'),
  (120,'dm22-003','魔龍バベルギヌス','魔龍バベルギヌス','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm22-003.jpg','hall'),
  (121,'dm13-s05','無双恐皇ガラムタ','無双恐皇ガラムタ','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm13-s05.jpg','hall'),
  (122,'dm10-009','無双竜機ボルバルザーク','無双竜機ボルバルザーク','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm10-009.jpg','premium_hall'),
  (123,'dmx21-066','目的不明の作戦','目的不明の作戦','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx21-066.jpg','hall'),
  (124,'dm08-008','予言者マリエル','予言者マリエル','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm08-008.jpg','hall'),
  (125,'dm23rp2-S06','雷炎翔鎧バルピアレスク','雷炎翔鎧バルピアレスク','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dm23rp2-S06.jpg','premium_hall'),
  (126,'dmr22-017','裏切りの魔狼月下城','裏切りの魔狼月下城','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr22-017.jpg','premium_hall'),
  (127,'dmx12b-026','竜魔神王バルカディア・NEX','竜魔神王バルカディア・NEX','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmx12b-026.jpg','hall'),
  (128,'dmr16g-009','龍素知新','龍素知新','https://dm.takaratomy.co.jp/wp-content/card/cardimage/dmr16g-009.jpg','hall');

do $$ begin
  if (select count(*) from hall_release_card_sync) <> 128
    or (select count(*) from hall_release_card_sync where regulation='hall') <> 89
    or (select count(*) from hall_release_card_sync where regulation='premium_hall') <> 39 then
    raise exception 'HALL_RELEASE_SYNC_COUNT_MISMATCH';
  end if;
  if exists (
    select 1 from hall_release_card_sync s join public.cards c on c.normalized_name=s.normalized_name
    where (c.source_kind,c.source_key) is distinct from ('takaratomy_card_id',s.source_key)
  ) then raise exception 'HALL_RELEASE_NORMALIZED_NAME_COLLISION'; end if;
end $$;

insert into public.cards(name,normalized_name,image_url,civilization,cost,card_type,regulation,is_active,source_kind,source_key)
select name,normalized_name,image_url,'{}'::text[],null,null,regulation,true,'takaratomy_card_id',source_key
from hall_release_card_sync
on conflict do nothing;

do $$ begin
  if (select count(*) from hall_release_card_sync s join public.cards c
      on c.source_kind='takaratomy_card_id' and c.source_key=s.source_key and c.is_active) <> 128 then
    raise exception 'HALL_RELEASE_CARDS_NOT_FULLY_LINKED';
  end if;
end $$;
