create table if not exists public.admin_consented_post_metadata (
  id bigint generated by default as identity primary key,
  post_id bigint not null unique references public.posts(id) on delete cascade,
  is_admin_proxy boolean not null default true check (is_admin_proxy),
  permission_confirmed boolean not null default true check (permission_confirmed),
  permission_confirmed_on date not null,
  internal_memo text not null default '',
  text_state text not null check (text_state in ('original', 'lightly_edited')),
  registered_by text not null,
  registered_at timestamptz not null default now()
);

alter table public.admin_consented_post_metadata enable row level security;
revoke all on table public.admin_consented_post_metadata from anon, authenticated;
revoke all on sequence public.admin_consented_post_metadata_id_seq from anon, authenticated;

create or replace function public.admin_create_consented_thread(
  p_title text, p_body text, p_author_name text, p_image_url text,
  p_thumbnail_url text, p_image_width integer, p_image_height integer,
  p_comments jsonb, p_registered_by text
) returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  v_thread_id bigint;
  v_comment jsonb;
  v_post_id bigint;
  v_number integer := 2;
  v_now timestamptz := clock_timestamp();
begin
  if p_author_name is distinct from '名無しのデュエリスト' then raise exception 'invalid author'; end if;
  if p_registered_by is distinct from 'admin-cookie' then raise exception 'invalid administrator'; end if;
  if length(trim(p_title)) = 0 or length(p_title) > 100 then raise exception 'invalid title'; end if;
  if length(coalesce(p_body, '')) > 5000 then raise exception 'invalid body'; end if;
  if jsonb_typeof(p_comments) <> 'array' or jsonb_array_length(p_comments) > 50 then raise exception 'invalid comments'; end if;

  insert into public.threads(title, body, author_name, image_url, thumbnail_url, image_width, image_height, post_count, created_at, last_posted_at)
  values (trim(p_title), coalesce(trim(p_body), ''), p_author_name, p_image_url, p_thumbnail_url, p_image_width, p_image_height,
          jsonb_array_length(p_comments) + 1, v_now, v_now)
  returning id into v_thread_id;

  for v_comment in select value from jsonb_array_elements(p_comments)
  loop
    if length(trim(v_comment->>'body')) = 0 then continue; end if;
    if length(v_comment->>'body') > 5000 then raise exception 'invalid comment'; end if;
    insert into public.posts(thread_id, post_number, body, author_name, created_at)
    values (v_thread_id, v_number, trim(v_comment->>'body'), p_author_name, v_now + ((v_number - 1) * interval '1 millisecond'))
    returning id into v_post_id;
    insert into public.admin_consented_post_metadata(post_id, permission_confirmed_on, internal_memo, text_state, registered_by, registered_at)
    values (v_post_id, (v_comment->>'permission_confirmed_on')::date, coalesce(v_comment->>'internal_memo', ''),
            v_comment->>'text_state', p_registered_by, v_now);
    v_number := v_number + 1;
  end loop;

  update public.threads set post_count = v_number - 1,
    last_posted_at = case when v_number > 2 then v_now + ((v_number - 2) * interval '1 millisecond') else v_now end
  where id = v_thread_id;
  return v_thread_id;
end;
$$;

revoke all on function public.admin_create_consented_thread(text,text,text,text,text,integer,integer,jsonb,text) from public, anon, authenticated;
grant execute on function public.admin_create_consented_thread(text,text,text,text,text,integer,integer,jsonb,text) to service_role;
